# Generated by Django 4.0.6 on 2022-08-03 07:01

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время, когда запись была создана', verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата, когда запись была последний раз обновлена', verbose_name='Обновлено')),
                ('published', models.BooleanField(default=False, help_text='Опубликовать запись или нет', verbose_name='Опубликовано?')),
                ('order', models.IntegerField(verbose_name='Порядок')),
                ('homework_id', models.AutoField(help_text='Уникальный идентификатор домашнего задания', primary_key=True, serialize=False, verbose_name='ID домашнего задания')),
                ('text', ckeditor.fields.RichTextField(help_text='HTML вариан описания домашки', verbose_name='Описание домашнего задания')),
                ('file', models.FileField(help_text='Файл, в котором хранится вся небходимая информация для домашнего задания', upload_to='media/homework/task/files', verbose_name='Файл домашнего задания')),
            ],
            options={
                'verbose_name': 'Домашнее задание',
                'verbose_name_plural': 'Домашние задания',
            },
        ),
        migrations.CreateModel(
            name='UserHomework',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время, когда запись была создана', verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата, когда запись была последний раз обновлена', verbose_name='Обновлено')),
                ('user_homework_id', models.AutoField(editable=False, help_text='Уникальный идентификатор выполненной домашней работы', primary_key=True, serialize=False, verbose_name='ID выполненного домашнего задания')),
                ('text', models.TextField(help_text='Ответ ученика на домашнее задание', verbose_name='Ответ ученика')),
                ('status', models.CharField(choices=[('ПРИ', 'Пришёл'), ('ПРО', 'Проверен'), ('НЕП', 'Неправильно'), ('ПРА', 'Правильно')], default='ПРИ', help_text='Статус отправленной домашки', max_length=256, verbose_name='Статус')),
                ('file', models.FileField(help_text='Файл, в котором содержится ответ на домашнюю работу', upload_to='media/homework/task/answers', verbose_name='Файл ответа')),
                ('mark', models.IntegerField(blank=True, help_text='Отметка за домашнюю работу', null=True, verbose_name='Отметка')),
                ('teacher_message', models.TextField(blank=True, help_text='Комментарий преподавателя по проделанной работе', null=True, verbose_name='Комментарий')),
                ('homework', models.ForeignKey(help_text='ID домашнего задания, ответ на который прислали', on_delete=django.db.models.deletion.CASCADE, related_name='user_homeworks', to='homeworks.homework', verbose_name='ID домашнего задания')),
            ],
            options={
                'verbose_name': 'Сданная домашка',
                'verbose_name_plural': 'Сданные домашки',
            },
        ),
    ]
