# Generated by Django 4.0.6 on 2022-08-03 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homeworks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhomework',
            name='teacher',
            field=models.ForeignKey(help_text='Учитель, который проверял домашнюю работы', on_delete=django.db.models.deletion.CASCADE, related_name='teacher_homeworks', to=settings.AUTH_USER_MODEL, verbose_name='ID учителя'),
        ),
        migrations.AddField(
            model_name='userhomework',
            name='user',
            field=models.ForeignKey(help_text='ID ученика, выполнившего домашнюю работу', on_delete=django.db.models.deletion.CASCADE, related_name='user_homeworks', to=settings.AUTH_USER_MODEL, verbose_name='ID ученика'),
        ),
        migrations.AddField(
            model_name='homework',
            name='author_id',
            field=models.ForeignKey(help_text='Автор записи', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='homework',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='courses.lesson', verbose_name='Домашнее задание'),
        ),
    ]
