# Generated by Django 4.0.6 on 2022-07-13 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0002_initial'),
        ('homeworks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhomework',
            name='teacher_id',
            field=models.ForeignKey(default=1, help_text='Учитель, который проверял домашнюю работы', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='user_homework_teacher_id_fk', to=settings.AUTH_USER_MODEL, verbose_name='ID учителя'),
        ),
        migrations.AddField(
            model_name='userhomework',
            name='user_id',
            field=models.ForeignKey(default=1, help_text='ID ученика, выолнившего домашнюю работу', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='user_homework_user_id_fk', to=settings.AUTH_USER_MODEL, verbose_name='ID ученика'),
        ),
        migrations.AddField(
            model_name='homework',
            name='lesson_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_lesson_id_fk', to='courses.lesson', verbose_name='Домашнее задание'),
        ),
    ]
