# Generated by Django 4.0.6 on 2022-07-29 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homeworks', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhomework',
            name='user',
            field=models.ForeignKey(help_text='ID ученика, выполнившего домашнюю работу', on_delete=django.db.models.deletion.CASCADE, related_name='user_homeworks', to=settings.AUTH_USER_MODEL, verbose_name='ID ученика'),
        ),
    ]
