# Generated by Django 4.0.6 on 2022-07-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('lms_Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='permissions',
            field=models.ManyToManyField(to='auth.permission'),
        ),
    ]
