# Generated by Django 4.0.6 on 2022-07-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_Users', '0002_roles_permissions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roles',
            old_name='permissions',
            new_name='user_permissions',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
