# Generated by Django 4.1.1 on 2023-10-05 11:24

import common_services.services.file_validation
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="APIRequestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requested_at", models.DateTimeField(db_index=True)),
                ("response_ms", models.PositiveIntegerField(default=0)),
                ("path", models.CharField(db_index=True, max_length=200)),
                (
                    "view",
                    models.CharField(
                        blank=True, db_index=True, max_length=200, null=True
                    ),
                ),
                (
                    "view_method",
                    models.CharField(
                        blank=True, db_index=True, max_length=27, null=True
                    ),
                ),
                ("remote_addr", models.GenericIPAddressField()),
                ("host", models.URLField()),
                ("method", models.CharField(max_length=10)),
                ("query_params", models.TextField(blank=True, null=True)),
                ("data", models.TextField(blank=True, null=True)),
                ("response", models.TextField(blank=True, null=True)),
                ("errors", models.TextField(blank=True, null=True)),
                ("status_code", models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "API Request Log",
            },
        ),
        migrations.CreateModel(
            name="AudioFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Дата и время, когда запись была создана",
                        verbose_name="Создано",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Дата, когда запись была последний раз обновлена",
                        verbose_name="Обновлено",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="",
                        validators=[
                            common_services.services.file_validation.limit_size
                        ],
                        verbose_name="Ресурс",
                    ),
                ),
            ],
            options={
                "verbose_name": "Аудиофайл",
                "verbose_name_plural": "Аудиофайлы",
                "default_related_name": "audio_files",
            },
        ),
        migrations.CreateModel(
            name="TextFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Дата и время, когда запись была создана",
                        verbose_name="Создано",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Дата, когда запись была последний раз обновлена",
                        verbose_name="Обновлено",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="",
                        validators=[
                            common_services.services.file_validation.limit_size
                        ],
                        verbose_name="Ресурс",
                    ),
                ),
            ],
            options={
                "verbose_name": "Текстовый файл",
                "verbose_name_plural": "Текстовые файлы",
                "default_related_name": "text_files",
            },
        ),
    ]
