# Generated by Django 4.1.1 on 2023-10-05 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("common_services", "0001_initial"),
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="textfile",
            name="author",
            field=models.ForeignKey(
                default=1,
                help_text="Автор записи",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AddField(
            model_name="textfile",
            name="base_lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.baselesson",
            ),
        ),
        migrations.AddField(
            model_name="textfile",
            name="user_homework",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.userhomework",
            ),
        ),
        migrations.AddField(
            model_name="textfile",
            name="user_homework_check",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.userhomeworkcheck",
            ),
        ),
        migrations.AddField(
            model_name="audiofile",
            name="author",
            field=models.ForeignKey(
                default=1,
                help_text="Автор записи",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AddField(
            model_name="audiofile",
            name="base_lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.baselesson",
            ),
        ),
        migrations.AddField(
            model_name="audiofile",
            name="user_homework",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.userhomework",
            ),
        ),
        migrations.AddField(
            model_name="audiofile",
            name="user_homework_check",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.userhomeworkcheck",
            ),
        ),
        migrations.AddField(
            model_name="apirequestlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
