# Generated by Django 4.1.1 on 2023-11-07 09:28

import common_services.services.file_validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common_services", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audiofile",
            name="file",
            field=models.FileField(
                max_length=300,
                upload_to="",
                validators=[common_services.services.file_validation.limit_size],
                verbose_name="Ресурс",
            ),
        ),
        migrations.AlterField(
            model_name="textfile",
            name="file",
            field=models.FileField(
                max_length=300,
                upload_to="",
                validators=[common_services.services.file_validation.limit_size],
                verbose_name="Ресурс",
            ),
        ),
    ]
