from environs import Env
from huey import RedisHuey

env = Env()
env.read_env()

REDIS_HOST = env("REDIS_HOST")
REDIS_PORT = env("REDIS_PORT")

huey = RedisHuey(url=f"redis://{REDIS_HOST}:{REDIS_PORT}/2")

EMAIL_NAME = env.str("EMAIL_NAME")
EMAIL_PASSWORD = env.str("EMAIL_PASSWORD")

S3_SECRET_KEY = env.str("S3_SECRET_KEY")
S3_ACCESS_KEY = env.str("S3_ACCESS_KEY")
REGION_NAME = env.str("REGION_NAME")
ENDPOINT_URL = env.str("ENDPOINT_URL")
S3_BUCKET = env.str("S3_BUCKET")

POSTGRES_DB_NAME = env("POSTGRES_DB_NAME")
POSTGRES_USER = env("POSTGRES_USER")
POSTGRES_USER_PASSWORD = env("POSTGRES_USER_PASSWORD")
POSTGRES_HOST = env("POSTGRES_HOST")
POSTGRES_PORT = env("POSTGRES_PORT")
