repos:
  # python import sorting - will amend files
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.7.0
    hooks:
      - id: isort
        language_version: python3.9.1
        args: ["--profile", "black"]

  # python code formatting - will amend files
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        language_version: python3.9.1

  # Flake8 includes pyflakes, pycodestyle, mccabe, pydocstyle, bandit
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        language_version: python3.9.1
        exclude: __init__.py

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: check-ast
      - id: end-of-file-fixer
        exclude: requirements.txt
      - id: mixed-line-ending
        exclude: requirements.txt
