repos:
  # python import sorting - will amend files
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.7.0
    hooks:
    - id: isort
      language_version: python3.9.1

  # python code formatting - will amend files
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    - id: black
      language_version: python3.9.1

  # Flake8 includes pyflakes, pycodestyle, mccabe, pydocstyle, bandit
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
    - id: flake8
      language_version: python3.9.1
      exclude: __init__.py

  # PEP8 linting, with added Django goodness
#  - repo: https://github.com/pre-commit/mirrors-pylint
#    rev: v2.6.0
#    hooks:
#      - id: pylint
#        language_version: python3.9.1
