version: "3.3"

services:
  rabbitmq:
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
  redis:
    image: "redis:alpine"
    restart: always
    command: redis-server --requirepass sOmE_sEcUrE_pAsS
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/var/lib/redis
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
  back:
    build: overschool
    image: back
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    container_name: backendDjango
    ports:
      - "8000:8000"
    depends_on:
      - redis
  celery:
    restart: always
    build:
      context: overschool
    command: celery -A overschool worker -l info
    volumes:
      - ./app:/app
  celery-beat:
    build:
      context: overschool
    command: celery -A overschool beat -l info
    volumes:
      - .app:/app_beat
    depends_on:
      - redis
      - rabbitmq
