# Generated by Django 5.2.5 on 2025-08-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('provider_type', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Провайдер',
                'verbose_name_plural': 'Провайдеры',
            },
        ),
        migrations.CreateModel(
            name='BotResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='Ответ бота')),
                ('message_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата ответа')),
            ],
            options={
                'verbose_name': 'Ответ нейросети',
                'verbose_name_plural': 'Ответы нейросети',
            },
        ),
        migrations.CreateModel(
            name='OverAiChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_name', models.TextField(default='Новый чат', verbose_name='Имя чата')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения чата')),
            ],
            options={
                'verbose_name': 'OverAI чат',
                'verbose_name_plural': 'OverAI чаты',
            },
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_question', models.TextField(verbose_name='Контент сообщения')),
                ('message_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата сообщения')),
            ],
            options={
                'verbose_name': 'Сообщение пользователя',
                'verbose_name_plural': 'Сообщения пользователей',
            },
        ),
    ]
