# Generated by Django 4.1.1 on 2023-12-29 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chatgpt", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BotResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer", models.TextField(verbose_name="Ответ бота")),
                (
                    "message_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата ответа"),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Отправитель сообщения",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sender_question", models.TextField(verbose_name="Контент сообщения")),
                (
                    "message_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата сообщения"
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Отправитель сообщения",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="GptMessage",
        ),
    ]
