# Generated by Django 5.2.5 on 2025-08-11 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chatgpt', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='botresponse',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Отправитель сообщения'),
        ),
        migrations.AddField(
            model_name='overaichat',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Идентификатор пользователя'),
        ),
        migrations.AddField(
            model_name='botresponse',
            name='overai_chat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatgpt.overaichat', verbose_name='Идентификатор чата'),
        ),
        migrations.AddField(
            model_name='usermessage',
            name='overai_chat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatgpt.overaichat', verbose_name='Идентификатор чата'),
        ),
        migrations.AddField(
            model_name='usermessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Отправитель сообщения'),
        ),
    ]
