# Generated by Django 4.1.1 on 2024-01-09 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chatgpt", "0002_botresponse_usermessage_delete_gptmessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="OverAiChat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Идентификатор пользователя",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="botresponse",
            name="overai_chat_id",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="chatgpt.overaichat",
                verbose_name="Идентификатор чата",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="usermessage",
            name="overai_chat_id",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="chatgpt.overaichat",
                verbose_name="Идентификатор чата",
            ),
            preserve_default=False,
        ),
    ]
