# Generated by Django 4.1.1 on 2024-01-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatgpt", "0003_overaichat_botresponse_overai_chat_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="overaichat",
            name="chat_name",
            field=models.TextField(default="Новый чат", verbose_name="Имя чата"),
        ),
    ]
