# Generated by Django 4.1.1 on 2024-01-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatgpt", "0004_overaichat_chat_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=70)),
                ("provider_type", models.CharField(max_length=40)),
            ],
        ),
    ]
