# Generated by Django 4.1.1 on 2024-01-28 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatgpt", "0005_aiprovider"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aiprovider",
            options={"verbose_name": "Провайдер", "verbose_name_plural": "Провайдеры"},
        ),
        migrations.AlterModelOptions(
            name="botresponse",
            options={
                "verbose_name": "Ответ нейросети",
                "verbose_name_plural": "Ответы нейросети",
            },
        ),
        migrations.AlterModelOptions(
            name="overaichat",
            options={
                "verbose_name": "OverAI чат",
                "verbose_name_plural": "OverAI чаты",
            },
        ),
        migrations.AlterModelOptions(
            name="usermessage",
            options={
                "verbose_name": "Сообщение пользователя",
                "verbose_name_plural": "Сообщения пользователей",
            },
        ),
    ]
