# Generated by Django 4.1.1 on 2024-03-31 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatgpt", "0006_alter_aiprovider_options_alter_botresponse_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="overaichat",
            name="order",
            field=models.IntegerField(
                default=0, verbose_name="Порядок отображения чата"
            ),
        ),
    ]
