from .answer import AnswerAdmin
from .course import CourseAdmin
from .homework import HomeworkAdmin
from .lesson import LessonAdmin
from .question import QuestionAdmin
from .section import SectionAdmin
from .section_test import SectionTestAdmin
from .students_group import StudentsGroupAdmin
from .user_homework import UserHomeworkAdmin
