# Generated by Django 4.1.1 on 2023-10-05 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="confirmation_code",
        ),
        migrations.RemoveField(
            model_name="user",
            name="confirmation_code_created_at",
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активный"),
        ),
    ]
