# Generated by Django 4.1.1 on 2023-11-23 11:09

import common_services.services.file_validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_user_subscription_id_usersubscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="Аватар",
                max_length=300,
                null=True,
                upload_to="",
                validators=[common_services.services.file_validation.limit_size],
                verbose_name="Аватар",
            ),
        ),
    ]
