# Generated by Django 4.1.1 on 2023-11-29 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_email_alter_user_first_name_and_more"),
        ("users", "0005_alter_user_email_alter_user_first_name_and_more"),
    ]

    operations = []
