# Generated by Django 4.1.1 on 2023-12-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_merge_20231129_2136"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="patronymic",
            field=models.CharField(
                blank=True, default=None, max_length=150, verbose_name="Отчество"
            ),
        ),
    ]
