# Generated by Django 4.1.1 on 2023-12-26 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_user_patronymic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="patronymic",
            field=models.CharField(default="", max_length=150, verbose_name="Отчество"),
        ),
    ]
