# Generated by Django 4.1.1 on 2023-12-28 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_user_patronymic"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Documents",
        ),
    ]
