# Generated by Django 4.1.1 on 2024-01-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_delete_documents"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="patronymic",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Отчество"
            ),
        ),
    ]
