# Generated by Django 4.1.1 on 2024-01-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_alter_user_patronymic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Последняя активность"
            ),
        ),
    ]
