# Generated by Django 4.1.1 on 2024-01-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_alter_user_last_login"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="shown_welcome_message",
            field=models.BooleanField(
                default=False, verbose_name="Приветственное сообщение OVER AI"
            ),
        ),
    ]
