# Generated by Django 4.1.1 on 2024-02-21 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_userschooldocuments"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserSchoolDocuments",
        ),
    ]
