# Generated by Django 4.1.1 on 2024-02-28 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_delete_userschooldocuments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="Почта",
                max_length=254,
                unique=True,
                verbose_name="Почта",
            ),
        ),
    ]
