# Generated by Django 4.1.1 on 2024-04-02 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_alter_profile_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersubscription",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
