# Generated by Django 4.1.1 on 2024-05-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_usersubscription_expires_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="pseudonym",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Псевдоним"
            ),
        ),
    ]
