# Generated by Django 4.1.1 on 2024-05-02 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_user_pseudonym"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="pseudonym",
        ),
    ]
