# Generated by Django 4.1.1 on 2024-05-02 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_remove_user_pseudonym"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPseudonym",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pseudonym",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Псевдоним сотрудника",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pseudonyms_as_school",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pseudonyms_as_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Псевдоним сотрудника школы",
                "verbose_name_plural": "Псевдоним сотрудника школы",
            },
        ),
    ]
