# Generated by Django 4.1.1 on 2024-05-04 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0027_merge_20240430_1714"),
        ("users", "0020_userpseudonym"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpseudonym",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pseudonyms_as_school",
                to="schools.school",
            ),
        ),
    ]
