# Generated by Django 4.1.1 on 2024-05-12 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0021_alter_userpseudonym_school"),
    ]

    operations = [
        migrations.CreateModel(
            name="UtmLabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "utm_source",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Источник трафика",
                    ),
                ),
                (
                    "utm_medium",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Тип трафика",
                    ),
                ),
                (
                    "utm_campaign",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="Кампания"
                    ),
                ),
                (
                    "utm_content",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Контент ссылки",
                    ),
                ),
                (
                    "utm_term",
                    models.EmailField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Идентификатор элемента рекламного объявления",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="utm_labels_as_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "utm-метка",
                "verbose_name_plural": "utm-метки",
            },
        ),
    ]
