# Generated by Django 4.1.1 on 2024-10-14 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0022_utmlabel"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usergroup",
            options={
                "verbose_name": "Группа пользователя",
                "verbose_name_plural": "Группы пользователей",
            },
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(fields=["city"], name="users_profi_city_2fdd0b_idx"),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(fields=["sex"], name="users_profi_sex_929eed_idx"),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(fields=["user"], name="users_profi_user_id_783607_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["username"], name="users_user_usernam_65d164_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="users_user_email_6f2530_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["phone_number"], name="users_user_phone_n_7fe504_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["last_login"], name="users_user_last_lo_5f84ec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["date_joined"], name="users_user_date_jo_064c8f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["first_name"], name="users_user_first_n_0186c7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["last_name"], name="users_user_last_na_4e2935_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["patronymic"], name="users_user_patrony_bfbcdd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usergroup",
            index=models.Index(fields=["user"], name="users_userg_user_id_409369_idx"),
        ),
        migrations.AddIndex(
            model_name="usergroup",
            index=models.Index(fields=["group"], name="users_userg_group_i_88ab69_idx"),
        ),
        migrations.AddIndex(
            model_name="usergroup",
            index=models.Index(
                fields=["school"], name="users_userg_school__8aa69e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userpseudonym",
            index=models.Index(fields=["user"], name="users_userp_user_id_f960d3_idx"),
        ),
        migrations.AddIndex(
            model_name="userpseudonym",
            index=models.Index(
                fields=["school"], name="users_userp_school__fdf5ee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userpseudonym",
            index=models.Index(
                fields=["pseudonym"], name="users_userp_pseudon_1505d8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersubscription",
            index=models.Index(fields=["user"], name="users_users_user_id_91045e_idx"),
        ),
        migrations.AddIndex(
            model_name="usersubscription",
            index=models.Index(
                fields=["school"], name="users_users_school__9ddd3d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersubscription",
            index=models.Index(
                fields=["expires_at"], name="users_users_expires_4b1727_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="utmlabel",
            index=models.Index(fields=["user"], name="users_utmla_user_id_f43a29_idx"),
        ),
        migrations.AddIndex(
            model_name="utmlabel",
            index=models.Index(
                fields=["utm_source"], name="users_utmla_utm_sou_d135af_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="utmlabel",
            index=models.Index(
                fields=["utm_medium"], name="users_utmla_utm_med_727ba5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="utmlabel",
            index=models.Index(
                fields=["utm_campaign"], name="users_utmla_utm_cam_026cfb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="utmlabel",
            index=models.Index(
                fields=["utm_content"], name="users_utmla_utm_con_33dd06_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="utmlabel",
            index=models.Index(
                fields=["utm_term"], name="users_utmla_utm_ter_32c26f_idx"
            ),
        ),
    ]
