# Generated by Django 4.1.1 on 2024-12-05 08:46

import common_services.services.file_validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0023_alter_usergroup_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Дата и время, когда запись была создана",
                        verbose_name="Создано",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Дата, когда запись была последний раз обновлена",
                        verbose_name="Обновлено",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Имя пользователя",
                        max_length=100,
                        null=True,
                        verbose_name="Имя пользователя",
                    ),
                ),
                (
                    "surname",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Фамилия пользователя",
                        max_length=100,
                        null=True,
                        verbose_name="Фамилия пользователя",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Должность пользователя",
                        max_length=500,
                        null=True,
                        verbose_name="Должность пользователя",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Текст отзыва",
                        null=True,
                        verbose_name="Текст отзыва",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        help_text="Аватар",
                        max_length=300,
                        null=True,
                        upload_to=common_services.services.file_validation.TruncateFileName(
                            300
                        ),
                        validators=[
                            common_services.services.file_validation.limit_image_size
                        ],
                        verbose_name="Аватар",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        blank=True,
                        help_text="Рейтинг",
                        null=True,
                        verbose_name="Рейтинг",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отзыв о платформе",
                "verbose_name_plural": "Отзывы о платформе",
            },
        ),
    ]
