# Generated by Django 4.1.1 on 2024-12-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0024_feedback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="rating",
            field=models.IntegerField(
                blank=True,
                help_text="Рейтинг от 1 до 5",
                null=True,
                verbose_name="Рейтинг от 1 до 5",
            ),
        ),
    ]
