# Generated by Django 4.2.16 on 2025-07-06 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0025_alter_feedback_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone_set_by_manager",
            field=models.BooleanField(
                default=False, verbose_name="Номер телефона установлен менеджером"
            ),
        ),
    ]
