# Generated by Django 4.0.6 on 2022-07-21 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='user_id',
            field=models.ForeignKey(default=1, help_text='ID ученика по прогрессу на курсе', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='user_progress_user_id_fk', to=settings.AUTH_USER_MODEL, verbose_name='ID ученика'),
        ),
        migrations.AddField(
            model_name='section',
            name='course_id',
            field=models.ForeignKey(help_text='ID курса раздела', on_delete=django.db.models.deletion.CASCADE, related_name='course_section_id_fk', to='courses.course', verbose_name='ID курса'),
        ),
        migrations.AddField(
            model_name='section',
            name='previous_section_id',
            field=models.ForeignKey(help_text='ID предыдущего курса, если ID None - курс первый', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='section_id_fk', to='courses.section', verbose_name='ID прошлого раздела'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='previous_lesson_id',
            field=models.ForeignKey(help_text='Предыдущий урок, если None, значит, этот урок первый', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lesson_id_fk', to='courses.lesson', verbose_name='Предыдущий урок'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='section_id',
            field=models.ForeignKey(help_text='ID раздела курса', on_delete=django.db.models.deletion.CASCADE, related_name='section_lesson_id_fk', to='courses.section', verbose_name='ID раздела'),
        ),
    ]
