# Generated by Django 4.1.1 on 2023-10-05 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0001_initial"),
        ("chats", "0002_initial"),
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertest",
            name="user",
            field=models.ForeignKey(
                default=1,
                help_text="Уникальный идентификатор пользователя",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to=settings.AUTH_USER_MODEL,
                verbose_name="ID пользователя",
            ),
        ),
        migrations.AddField(
            model_name="userprogresslogs",
            name="lesson",
            field=models.ForeignKey(
                blank=True,
                help_text="ID урока/дз/теста, который был завершен",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_progresses",
                to="courses.baselesson",
                verbose_name="ID урока/дз/теста",
            ),
        ),
        migrations.AddField(
            model_name="userprogresslogs",
            name="user",
            field=models.ForeignKey(
                help_text="ID ученика по прогрессу на курсе",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_progresses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="ID ученика",
            ),
        ),
        migrations.AddField(
            model_name="userhomeworkcheck",
            name="author",
            field=models.ForeignKey(
                default=1,
                help_text="Автор записи",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AddField(
            model_name="userhomeworkcheck",
            name="user_homework",
            field=models.ForeignKey(
                help_text="ID домашнего задания, ответ на который прислали",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_homework_checks",
                to="courses.userhomework",
                verbose_name="ID домашнего задания студента",
            ),
        ),
        migrations.AddField(
            model_name="userhomework",
            name="teacher",
            field=models.ForeignKey(
                help_text="Учитель, который проверял домашнюю работы",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher_homeworks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="ID учителя",
            ),
        ),
        migrations.AddField(
            model_name="userhomework",
            name="user",
            field=models.ForeignKey(
                help_text="ID ученика, выполнившего домашнюю работу",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_homeworks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="ID ученика",
            ),
        ),
        migrations.AddField(
            model_name="studentstableinfo",
            name="author",
            field=models.ForeignKey(
                default=1,
                help_text="Автор записи",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AddField(
            model_name="studentstableinfo",
            name="school",
            field=models.ForeignKey(
                help_text="К какой школе относятся таблицы",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tables",
                to="schools.school",
                verbose_name="Школа",
            ),
        ),
        migrations.AddField(
            model_name="studentsgroup",
            name="chat",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group",
                to="chats.chat",
            ),
        ),
        migrations.AddField(
            model_name="studentsgroup",
            name="course_id",
            field=models.ForeignKey(
                help_text="Курс, который проходит эта группа",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_course_fk",
                to="courses.course",
                verbose_name="Курс",
            ),
        ),
        migrations.AddField(
            model_name="studentsgroup",
            name="group_settings",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students_group_settings_fk",
                to="courses.studentsgroupsettings",
            ),
        ),
        migrations.AddField(
            model_name="studentsgroup",
            name="students",
            field=models.ManyToManyField(
                help_text="Ученики этой группы",
                related_name="students_group_fk",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Ученики",
            ),
        ),
        migrations.AddField(
            model_name="studentsgroup",
            name="teacher_id",
            field=models.ForeignKey(
                help_text="Преподаватель, который ведёт эту группу",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher_group_fk",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Преподаватель",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="author",
            field=models.ForeignKey(
                default=1,
                help_text="Автор записи",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="course",
            field=models.ForeignKey(
                help_text="ID курса раздела",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="courses.course",
                verbose_name="ID курса",
            ),
        ),
        migrations.AddField(
            model_name="lessoncomponentsorder",
            name="base_lesson",
            field=models.ForeignKey(
                help_text="ID базового урока, к которому относится компонент с соответствующим порядком",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="all_components",
                to="courses.baselesson",
                verbose_name="ID базового урока",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="author",
            field=models.ForeignKey(
                default=1,
                help_text="Автор записи",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="school",
            field=models.ForeignKey(
                help_text="ID школы",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_school",
                to="schools.school",
                verbose_name="ID школы",
            ),
        ),
        migrations.AddField(
            model_name="baselesson",
            name="author",
            field=models.ForeignKey(
                default=1,
                help_text="Автор записи",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AddField(
            model_name="baselesson",
            name="section",
            field=models.ForeignKey(
                help_text="ID раздела курса",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="courses.section",
                verbose_name="ID раздела",
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="question",
            field=models.ForeignKey(
                help_text="Вопрос, к которому привязан ответ",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="courses.question",
                verbose_name="ID Вопроса",
            ),
        ),
        migrations.AddField(
            model_name="usertest",
            name="test",
            field=models.ForeignKey(
                help_text="Уникальный идентификатор теста",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tests",
                to="courses.sectiontest",
                verbose_name="ID теста",
            ),
        ),
        migrations.AddField(
            model_name="userhomework",
            name="homework",
            field=models.ForeignKey(
                help_text="ID домашнего задания, ответ на который прислали",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_homeworks",
                to="courses.homework",
                verbose_name="ID домашнего задания",
            ),
        ),
        migrations.AddConstraint(
            model_name="section",
            constraint=models.UniqueConstraint(
                fields=("course", "order"), name="unique_course_section_order"
            ),
        ),
        migrations.AddField(
            model_name="randomtesttests",
            name="target_test",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="target_test",
                to="courses.sectiontest",
            ),
        ),
        migrations.AddField(
            model_name="randomtesttests",
            name="test",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test",
                to="courses.sectiontest",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="test",
            field=models.ForeignKey(
                help_text="Тест, к которому привязан вопрос",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="courses.sectiontest",
                verbose_name="Тест",
            ),
        ),
        migrations.AddConstraint(
            model_name="lessoncomponentsorder",
            constraint=models.UniqueConstraint(
                fields=("base_lesson", "order"), name="unique_lesson_component_order"
            ),
        ),
        migrations.AddConstraint(
            model_name="course",
            constraint=models.UniqueConstraint(
                fields=("school", "order"), name="unique_school_course_order"
            ),
        ),
        migrations.AddConstraint(
            model_name="baselesson",
            constraint=models.UniqueConstraint(
                fields=("section", "order"), name="unique_section_lesson_order"
            ),
        ),
    ]
