# Generated by Django 4.2.6 on 2023-10-14 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="baselesson",
            name="url",
            field=models.URLField(
                blank=True,
                help_text="Ссылка на видео из YouTube",
                null=True,
                verbose_name="URL видео",
            ),
        ),
    ]
