# Generated by Django 4.1.1 on 2023-09-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sectiontest",
            name="success_percent",
            field=models.IntegerField(
                default=0,
                help_text="Процент правильных ответов для успешно пройденного теста",
                verbose_name="Проходной балл",
            ),
        ),
    ]
