# Generated by Django 4.0.6 on 2022-08-17 10:05

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Описание курса для отображения, сохраняется в html', null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration_days',
            field=models.PositiveIntegerField(blank=True, help_text='Продолжительность курса в днях', null=True, verbose_name='Продолжительность курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='format',
            field=models.CharField(blank=True, choices=[('ОФФ', 'Оффлайн'), ('ОН', 'Онлайн')], default='ОН', help_text='Формат курса, отображает формат обучения (Онлайн либо Оффлайн)', max_length=256, null=True, verbose_name='Формат курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(blank=True, help_text='Главное название курса', max_length=256, null=True, verbose_name='Название курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='photo',
            field=models.ImageField(blank=True, help_text='Главная фотография', null=True, upload_to='images/courses/main/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Цена курса в BYN', max_digits=15, null=True, verbose_name='Цена'),
        ),
        migrations.CreateModel(
            name='StudentsGroup',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время, когда запись была создана', verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата, когда запись была последний раз обновлена', verbose_name='Обновлено')),
                ('group_id', models.AutoField(help_text='Уникальный идентификатор группы', primary_key=True, serialize=False, verbose_name='Группа ID')),
                ('name', models.CharField(help_text='Название группы', max_length=256, verbose_name='Название группы')),
                ('course_id', models.ForeignKey(help_text='Курс, который проходит эта группа', on_delete=django.db.models.deletion.PROTECT, related_name='group_course_fk', to='courses.course', verbose_name='Курс')),
                ('students', models.ManyToManyField(help_text='Ученики этой группы', related_name='students_group_fk', to=settings.AUTH_USER_MODEL, verbose_name='Ученики')),
                ('teacher_id', models.ForeignKey(default=1, help_text='Преподаватель, который ведёт эту группу', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='teacher_group_fk', to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Группа студентов',
                'verbose_name_plural': 'Группы студентов',
            },
        ),
    ]
