# Generated by Django 4.1.1 on 2023-10-25 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_baselesson_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baselesson",
            name="video",
            field=models.FileField(
                blank=True,
                help_text="Видеофайл размером до 2 ГБ",
                max_length=300,
                null=True,
                upload_to="",
                verbose_name="Видео",
            ),
        ),
    ]
