# Generated by Django 4.1.1 on 2023-11-23 11:09

import common_services.services.file_validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_alter_baselesson_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="picture",
            field=models.ImageField(
                blank=True,
                max_length=300,
                null=True,
                upload_to="",
                validators=[common_services.services.file_validation.limit_size],
                verbose_name="Картинка",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Главная фотография",
                max_length=300,
                null=True,
                upload_to="",
                validators=[common_services.services.file_validation.limit_size],
                verbose_name="Фотография",
            ),
        ),
    ]
