# Generated by Django 4.1.1 on 2023-11-29 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_alter_answer_picture_alter_course_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentsgroup",
            name="type",
            field=models.CharField(
                choices=[
                    ("WITH_TEACHER", "С учителем"),
                    ("WITHOUT_TEACHER", "Без учителя"),
                ],
                default="WITH_TEACHER",
                help_text="Тип группы (С учителем / Без учителя)",
                max_length=20,
                verbose_name="Тип группы",
            ),
        ),
    ]
