# Generated by Django 4.1.1 on 2023-11-27 08:16

import common_services.services.file_validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_alter_answer_picture_alter_course_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="picture",
            field=models.ImageField(
                blank=True,
                max_length=300,
                null=True,
                upload_to=common_services.services.file_validation.TruncateFileName(
                    300
                ),
                validators=[common_services.services.file_validation.limit_size],
                verbose_name="Картинка",
            ),
        ),
        migrations.AlterField(
            model_name="baselesson",
            name="video",
            field=models.FileField(
                blank=True,
                help_text="Видеофайл размером до 2 ГБ",
                max_length=300,
                null=True,
                upload_to=common_services.services.file_validation.TruncateFileName(
                    300
                ),
                verbose_name="Видео",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Главная фотография",
                max_length=300,
                null=True,
                upload_to=common_services.services.file_validation.TruncateFileName(
                    300
                ),
                validators=[common_services.services.file_validation.limit_size],
                verbose_name="Фотография",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=common_services.services.file_validation.TruncateFileName(
                    300
                ),
                validators=[common_services.services.file_validation.limit_size],
                verbose_name="Картинка",
            ),
        ),
    ]
