# Generated by Django 4.1.1 on 2023-11-29 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0006_alter_answer_picture_alter_baselesson_video_and_more"),
        ("courses", "0006_studentsgroup_type"),
    ]

    operations = []
