# Generated by Django 4.1.1 on 2023-11-30 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0007_merge_20231129_2136"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentsgroup",
            name="students",
            field=models.ManyToManyField(
                blank=True,
                help_text="Ученики этой группы",
                related_name="students_group_fk",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Ученики",
            ),
        ),
        migrations.AlterField(
            model_name="studentsgroup",
            name="teacher_id",
            field=models.ForeignKey(
                blank=True,
                help_text="Преподаватель, который ведёт эту группу",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher_group_fk",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Преподаватель",
            ),
        ),
    ]
