# Generated by Django 4.1.1 on 2023-12-03 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0008_alter_studentsgroup_students_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentsHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_added",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Дата добавления в группу",
                        verbose_name="Дата добавления в группу",
                    ),
                ),
                (
                    "date_removed",
                    models.DateTimeField(
                        blank=True,
                        help_text="Дата удаления из группы",
                        null=True,
                        verbose_name="Дата удаления из группы",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="Студент удален из группы",
                        verbose_name="Студент удален из группы",
                    ),
                ),
                (
                    "students_group",
                    models.ForeignKey(
                        help_text="Группа студентов",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students_group",
                        to="courses.studentsgroup",
                        verbose_name="Группа студентов",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="ID ученика",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_history",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ID ученика",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student history",
                "verbose_name_plural": "Student history",
            },
        ),
    ]
