# Generated by Django 4.1.1 on 2023-12-10 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "courses",
            "0010_baselesson_available_for_students_lessonavailability_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userlessonsettings",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="userlessonsettings",
            name="lesson",
        ),
        migrations.RemoveField(
            model_name="userlessonsettings",
            name="user",
        ),
        migrations.AlterUniqueTogether(
            name="usertestsettings",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="usertestsettings",
            name="test",
        ),
        migrations.RemoveField(
            model_name="usertestsettings",
            name="user",
        ),
        migrations.DeleteModel(
            name="UserHomeworkSettings",
        ),
        migrations.DeleteModel(
            name="UserLessonSettings",
        ),
        migrations.DeleteModel(
            name="UserTestSettings",
        ),
    ]
