# Generated by Django 4.1.1 on 2023-12-12 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0011_alter_userlessonsettings_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="baselesson",
            name="available_for_students",
        ),
    ]
