# Generated by Django 4.1.1 on 2023-12-23 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0012_remove_baselesson_available_for_students"),
    ]

    operations = [
        migrations.CreateModel(
            name="LessonEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.baselesson",
                        verbose_name="Урок/ДЗ/Тест",
                    ),
                ),
                (
                    "student_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_enrollment",
                        to="courses.studentsgroup",
                        verbose_name="Группа студента",
                    ),
                ),
            ],
            options={
                "verbose_name": "Доступность урока для группы",
                "verbose_name_plural": "Доступность урока для группы",
            },
        ),
    ]
