# Generated by Django 4.1.1 on 2023-12-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0013_lessonenrollment"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentsgroup",
            name="certificate",
            field=models.BooleanField(
                default=False,
                help_text="Могут ли участники этой группы видеть сертификаты",
                verbose_name="Доступ к сертификатам",
            ),
        ),
    ]
