# Generated by Django 4.1.1 on 2023-12-27 12:28

import ckeditor.fields
import common_services.services.file_validation
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0014_studentsgroup_certificate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="baselesson",
            name="code",
        ),
        migrations.RemoveField(
            model_name="baselesson",
            name="description",
        ),
        migrations.RemoveField(
            model_name="baselesson",
            name="url",
        ),
        migrations.RemoveField(
            model_name="baselesson",
            name="video",
        ),
        migrations.CreateModel(
            name="BaseLessonVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(blank=True, verbose_name="Порядок")),
                (
                    "video",
                    models.FileField(
                        blank=True,
                        help_text="Видеофайл размером до 2 ГБ",
                        max_length=300,
                        null=True,
                        upload_to=common_services.services.file_validation.TruncateFileName(
                            300
                        ),
                        verbose_name="Видео",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="Ссылка на видео из YouTube",
                        null=True,
                        verbose_name="URL видео",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="courses.baselesson",
                    ),
                ),
            ],
            options={
                "verbose_name": "Видеофайл урока",
                "verbose_name_plural": "Видеофайлы уроков",
            },
        ),
        migrations.CreateModel(
            name="BaseLessonText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(blank=True, verbose_name="Порядок")),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Описание к уроку", verbose_name="Описание"
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="texts",
                        to="courses.baselesson",
                    ),
                ),
            ],
            options={
                "verbose_name": "Текст урока",
                "verbose_name_plural": "Тексты уроков",
            },
        ),
        migrations.CreateModel(
            name="BaseLessonPicture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(blank=True, verbose_name="Порядок")),
                (
                    "picture",
                    models.ImageField(
                        help_text="Картинка к уроку",
                        upload_to=common_services.services.file_validation.TruncateFileName(
                            300
                        ),
                        verbose_name="Картинка",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pictures",
                        to="courses.baselesson",
                    ),
                ),
            ],
            options={
                "verbose_name": "Картинка урока",
                "verbose_name_plural": "Картинки уроков",
            },
        ),
        migrations.CreateModel(
            name="BaseLessonCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(blank=True, verbose_name="Порядок")),
                (
                    "code",
                    ckeditor.fields.RichTextField(
                        help_text="Примеры кода к уроку", verbose_name="Код"
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="codes",
                        to="courses.baselesson",
                    ),
                ),
            ],
            options={
                "verbose_name": "Код урока",
                "verbose_name_plural": "Коды уроков",
            },
        ),
    ]
