# Generated by Django 4.1.1 on 2023-12-28 07:37

import ckeditor.fields
import common_services.services.file_validation
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "courses",
            "0015_remove_baselesson_code_remove_baselesson_description_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="BaseLessonBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(blank=True, verbose_name="Порядок")),
                (
                    "video",
                    models.FileField(
                        blank=True,
                        help_text="Видеофайл размером до 2 ГБ",
                        max_length=300,
                        null=True,
                        upload_to=common_services.services.file_validation.TruncateFileName(
                            300
                        ),
                        verbose_name="Видео",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="Ссылка на видео из YouTube",
                        null=True,
                        verbose_name="URL видео",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        blank=True,
                        help_text="Описание к уроку",
                        null=True,
                        verbose_name="Описание",
                    ),
                ),
                (
                    "code",
                    ckeditor.fields.RichTextField(
                        blank=True,
                        help_text="Примеры кода к уроку",
                        null=True,
                        verbose_name="Код",
                    ),
                ),
                (
                    "picture",
                    models.ImageField(
                        blank=True,
                        help_text="Картинка к уроку",
                        null=True,
                        upload_to=common_services.services.file_validation.TruncateFileName(
                            300
                        ),
                        verbose_name="Картинка",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="courses.baselesson",
                    ),
                ),
            ],
            options={
                "verbose_name": "Блок урока",
                "verbose_name_plural": "Блоки уроков",
            },
        ),
        migrations.RemoveField(
            model_name="baselessonpicture",
            name="lesson",
        ),
        migrations.RemoveField(
            model_name="baselessontext",
            name="lesson",
        ),
        migrations.RemoveField(
            model_name="baselessonvideo",
            name="lesson",
        ),
        migrations.DeleteModel(
            name="BaseLessonCode",
        ),
        migrations.DeleteModel(
            name="BaseLessonPicture",
        ),
        migrations.DeleteModel(
            name="BaseLessonText",
        ),
        migrations.DeleteModel(
            name="BaseLessonVideo",
        ),
    ]
