# Generated by Django 4.1.1 on 2023-12-28 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0016_baselessonblock_remove_baselessonpicture_lesson_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LessonComponentsOrder",
        ),
    ]
