# Generated by Django 4.1.1 on 2023-12-28 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0017_delete_lessoncomponentsorder"),
    ]

    operations = [
        migrations.RenameField(
            model_name="baselessonblock",
            old_name="lesson",
            new_name="base_lesson",
        ),
    ]
