# Generated by Django 4.1.1 on 2024-01-11 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0018_rename_lesson_baselessonblock_base_lesson"),
    ]

    operations = [
        migrations.AddField(
            model_name="baselessonblock",
            name="type",
            field=models.CharField(
                choices=[
                    ("video", "video"),
                    ("picture", "picture"),
                    ("description", "description"),
                    ("code", "code"),
                ],
                default="description",
                help_text="Тип блока",
                max_length=15,
                verbose_name="Тип блока",
            ),
        ),
    ]
