# Generated by Django 4.1.1 on 2024-01-25 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0019_baselessonblock_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="baselessonblock",
            name="language",
            field=models.CharField(
                blank=True,
                help_text="Язык программирования",
                max_length=200,
                null=True,
                verbose_name="Язык программирования",
            ),
        ),
    ]
