# Generated by Django 4.1.1 on 2024-02-21 08:54

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0020_baselessonblock_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="is_catalog",
            field=models.BooleanField(
                default=True,
                help_text="Видимость в каталоге курсов",
                verbose_name="Видимость в каталоге курсов",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(
                editable=False, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["search_vector"], name="courses_cou_search__cca690_idx"
            ),
        ),
    ]
