# Generated by Django 4.1.1 on 2024-02-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0022_courseappeals"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseappeals",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
    ]
