# Generated by Django 4.1.1 on 2024-02-22 13:46

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0023_courseappeals_is_read"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="courseappeals",
            options={
                "verbose_name": "Заявка на курс",
                "verbose_name_plural": "Заявки на курс",
            },
        ),
        migrations.AlterField(
            model_name="courseappeals",
            name="course",
            field=models.ForeignKey(
                help_text="ID курса",
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.course",
                verbose_name="ID курса",
            ),
        ),
        migrations.AlterField(
            model_name="courseappeals",
            name="email",
            field=models.EmailField(
                help_text="E-mail пользователя",
                max_length=254,
                verbose_name="E-mail пользователя",
            ),
        ),
        migrations.AlterField(
            model_name="courseappeals",
            name="is_read",
            field=models.BooleanField(
                default=False, help_text="Прочитано", verbose_name="Прочитано"
            ),
        ),
        migrations.AlterField(
            model_name="courseappeals",
            name="message",
            field=models.TextField(
                blank=True, help_text="Сообщение", null=True, verbose_name="Сообщение"
            ),
        ),
        migrations.AlterField(
            model_name="courseappeals",
            name="name",
            field=models.CharField(help_text="Имя", max_length=256, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="courseappeals",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                help_text="Телефон пользователя",
                max_length=128,
                region=None,
                verbose_name="Телефон пользователя",
            ),
        ),
    ]
