# Generated by Django 4.1.1 on 2024-02-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0024_alter_courseappeals_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="is_catalog",
            field=models.BooleanField(
                default=False,
                help_text="Видимость в каталоге курсов",
                verbose_name="Видимость в каталоге курсов",
            ),
        ),
    ]
