# Generated by Django 4.1.1 on 2024-03-09 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0025_alter_course_is_catalog"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentsgroup",
            name="training_duration",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Лимит продолжительности обучения в днях",
                verbose_name="Продолжительность обучения",
            ),
        ),
        migrations.CreateModel(
            name="TrainingDuration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "limit",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Лимит продолжительности обучения в днях",
                        verbose_name="Продолжительность обучения",
                    ),
                ),
                (
                    "students_group",
                    models.ForeignKey(
                        help_text="Группа студентов",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.studentsgroup",
                        verbose_name="Группа студентов",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="ID ученика",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_duration",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ID ученика",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продолжительность обучения",
                "verbose_name_plural": "Продолжительность обучения",
            },
        ),
    ]
