# Generated by Django 4.1.1 on 2024-03-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0025_alter_course_is_catalog"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="is_direct",
            field=models.BooleanField(
                default=False,
                help_text="Позволяет получить доступ к курсу по прямой ссылке",
                verbose_name="Доступ по прямой ссылке",
            ),
        ),
    ]
