# Generated by Django 4.1.1 on 2024-03-11 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0026_course_is_direct"),
        ("courses", "0026_studentsgroup_training_duration_trainingduration"),
    ]

    operations = []
