# Generated by Django 4.1.1 on 2024-03-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0027_merge_20240311_0951"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentsgroupsettings",
            name="overai_lock",
            field=models.BooleanField(
                default=False,
                help_text="При 'True' - OVER AI включен для учеников данной группы",
                verbose_name="Блокировка доступа к OVER AI",
            ),
        ),
    ]
