# Generated by Django 4.1.1 on 2024-03-18 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0028_studentsgroupsettings_overai_lock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentsgroupsettings",
            name="overai_lock",
            field=models.BooleanField(
                default=True,
                help_text="При 'True' - OVER AI включен для учеников данной группы",
                verbose_name="Блокировка доступа к OVER AI",
            ),
        ),
    ]
