# Generated by Django 4.1.1 on 2024-03-26 20:45

import common_services.services.file_validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0029_alter_studentsgroupsettings_overai_lock"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="studentshistory",
            options={
                "verbose_name": "История студента",
                "verbose_name_plural": "История студентов",
            },
        ),
        migrations.AlterField(
            model_name="answer",
            name="picture",
            field=models.ImageField(
                blank=True,
                max_length=300,
                null=True,
                upload_to=common_services.services.file_validation.TruncateFileName(
                    300
                ),
                validators=[common_services.services.file_validation.limit_image_size],
                verbose_name="Картинка",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Главная фотография",
                max_length=300,
                null=True,
                upload_to=common_services.services.file_validation.TruncateFileName(
                    300
                ),
                validators=[common_services.services.file_validation.limit_image_size],
                verbose_name="Фотография",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=common_services.services.file_validation.TruncateFileName(
                    300
                ),
                validators=[common_services.services.file_validation.limit_image_size],
                verbose_name="Картинка",
            ),
        ),
    ]
