# Generated by Django 4.1.1 on 2024-04-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0030_alter_studentshistory_options_alter_answer_picture_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="baselessonblock",
            name="formula",
            field=models.CharField(
                blank=True,
                help_text="Формула",
                max_length=500,
                null=True,
                verbose_name="Формула",
            ),
        ),
        migrations.AlterField(
            model_name="baselessonblock",
            name="type",
            field=models.CharField(
                choices=[
                    ("video", "video"),
                    ("picture", "picture"),
                    ("description", "description"),
                    ("code", "code"),
                    ("formula", "formula"),
                ],
                default="description",
                help_text="Тип блока",
                max_length=15,
                verbose_name="Тип блока",
            ),
        ),
    ]
