# Generated by Django 4.1.1 on 2024-04-09 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0031_baselessonblock_formula_alter_baselessonblock_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baselessonblock",
            name="type",
            field=models.CharField(
                choices=[
                    ("video", "video"),
                    ("picture", "picture"),
                    ("description", "description"),
                    ("code", "code"),
                    ("formula", "formula"),
                    ("buttons", "buttons"),
                ],
                default="description",
                help_text="Тип блока",
                max_length=15,
                verbose_name="Тип блока",
            ),
        ),
        migrations.CreateModel(
            name="BlockButton",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Текст кнопки",
                        max_length=200,
                        verbose_name="Текст кнопки",
                    ),
                ),
                (
                    "link",
                    models.URLField(
                        help_text="Ссылка для перехода по кнопке",
                        max_length=500,
                        verbose_name="Ссылка",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        help_text="Цвет кнопки",
                        max_length=50,
                        null=True,
                        verbose_name="Цвет кнопки",
                    ),
                ),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buttons",
                        to="courses.baselessonblock",
                    ),
                ),
            ],
            options={
                "verbose_name": "Кнопка блока урока",
                "verbose_name_plural": "Кнопки блока урока",
            },
        ),
    ]
