# Generated by Django 4.1.1 on 2024-04-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0031_baselessonblock_formula_alter_baselessonblock_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentsgroupsettings",
            name="overai_lock",
            field=models.BooleanField(
                default=False,
                help_text="При 'True' - OVER AI включен для учеников данной группы",
                verbose_name="Блокировка доступа к OVER AI",
            ),
        ),
    ]
