# Generated by Django 4.1.1 on 2024-04-12 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0032_alter_baselessonblock_type_blockbutton"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentsgroupsettings",
            name="submit_homework_to_go_on",
            field=models.BooleanField(
                default=False,
                help_text="При 'True' - ученики данной группы могут двигаться по курсу дальше только после отправки очередной выполненной домашней работы",
                verbose_name="Необходимость отправки д/з для перехода к следующим урокам",
            ),
        ),
        migrations.AddField(
            model_name="studentsgroupsettings",
            name="submit_test_to_go_on",
            field=models.BooleanField(
                default=False,
                help_text="При 'True' - ученики данной группы не могут двигаться по курсу дальше, пока не отправят свой вариант прохождения очередного теста",
                verbose_name="Необходимость прохождения теста для перехода к следующим урокам",
            ),
        ),
        migrations.AddField(
            model_name="studentsgroupsettings",
            name="success_test_to_go_on",
            field=models.BooleanField(
                default=False,
                help_text="При 'True' - ученики данной группы не могут двигаться по курсу дальше, пока не наберут необходимый процент правильных ответов очередного теста",
                verbose_name="Необходимость успешного прохождения теста для перехода к следующим урокам",
            ),
        ),
    ]
