# Generated by Django 4.1.1 on 2024-04-11 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0032_alter_baselessonblock_type_blockbutton"),
        ("courses", "0032_alter_studentsgroupsettings_overai_lock"),
    ]

    operations = []
