# Generated by Django 4.1.1 on 2024-04-14 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0033_merge_20240411_1449"),
        ("courses", "0033_studentsgroupsettings_submit_homework_to_go_on_and_more"),
    ]

    operations = []
