# Generated by Django 4.1.1 on 2024-04-16 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0034_merge_20240414_0931"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blockbutton",
            name="link",
            field=models.URLField(
                blank=True,
                help_text="Ссылка для перехода по кнопке",
                max_length=500,
                null=True,
                verbose_name="Ссылка",
            ),
        ),
    ]
