# Generated by Django 4.1.1 on 2024-04-16 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0035_alter_blockbutton_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Содержание комментария",
                        verbose_name="Содержание комментария",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Дата создания комментария",
                        verbose_name="Дата создания комментария",
                    ),
                ),
                (
                    "public",
                    models.BooleanField(
                        default=False,
                        help_text="Опубликован ли комментарий",
                        verbose_name="Опубликован ли комментарий",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="Автор комментария",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор комментария",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        help_text="Урок, к которому относится комментарий",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="courses.baselesson",
                        verbose_name="Урок, к которому относится комментарий",
                    ),
                ),
            ],
            options={
                "verbose_name": "Комментарий",
                "verbose_name_plural": "Комментарии",
            },
        ),
    ]
