# Generated by Django 4.1.1 on 2024-04-23 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0035_remove_section_unique_course_section_order_and_more"),
        ("courses", "0036_comment"),
    ]

    operations = []
