# Generated by Django 4.1.1 on 2024-05-02 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0037_merge_20240423_0604"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupCourseAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="courses.course"
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.studentsgroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Разрешение на курс",
                "verbose_name_plural": "Разрешения на курсы",
            },
        ),
    ]
