# Generated by Django 4.1.1 on 2024-05-07 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0038_groupcourseaccess"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="groupcourseaccess",
            options={
                "verbose_name": "Доступ к курсу для группы",
                "verbose_name_plural": "Доступы к курсам для групп",
            },
        ),
        migrations.AddField(
            model_name="groupcourseaccess",
            name="current_group",
            field=models.ForeignKey(
                default=5,
                help_text="Группа, для которой предоставлен доступ к курсу",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="current_group_accesses",
                to="courses.studentsgroup",
                verbose_name="Текущая группа",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="groupcourseaccess",
            name="course",
            field=models.ForeignKey(
                help_text="Курс, к которому предоставлен доступ",
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.course",
                verbose_name="Курс",
            ),
        ),
        migrations.AlterField(
            model_name="groupcourseaccess",
            name="group",
            field=models.ForeignKey(
                help_text="Группа на курсе, на которую предоставлен доступ",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_accesses",
                to="courses.studentsgroup",
                verbose_name="Новая группа на курсе",
            ),
        ),
    ]
