# Generated by Django 4.1.1 on 2024-06-04 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0039_alter_groupcourseaccess_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Folder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Название папки",
                        max_length=256,
                        verbose_name="Название папка",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="course",
            name="folder",
            field=models.ForeignKey(
                blank=True,
                help_text="ID папки",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="course_folder",
                to="courses.folder",
                verbose_name="ID папки",
            ),
        ),
    ]
