# Generated by Django 4.1.1 on 2024-06-05 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0034_alter_domain_options_alter_domain_domain_name_and_more"),
        ("courses", "0040_folder_course_folder"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="folder",
            options={"verbose_name": "Папка", "verbose_name_plural": "Папки"},
        ),
        migrations.AddField(
            model_name="folder",
            name="school",
            field=models.ForeignKey(
                default=77,
                help_text="ID школы",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="folder_school",
                to="schools.school",
                verbose_name="ID школы",
            ),
            preserve_default=False,
        ),
    ]
