# Generated by Django 4.1.1 on 2024-06-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0041_alter_folder_options_folder_school"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentshistory",
            name="finish_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Дата завершения обучения",
                null=True,
                verbose_name="Дата завершения обучения",
            ),
        ),
    ]
