# Generated by Django 4.1.1 on 2024-06-15 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0043_audienceblock_blockcards_headerblock_statsblock_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="courselanding",
            options={
                "verbose_name": "Блок с лендингом курса",
                "verbose_name_plural": "Блоки с лендингом курсов",
            },
        ),
        migrations.AddField(
            model_name="blockcards",
            name="position",
            field=models.IntegerField(
                default=0,
                help_text="Номер следования в списке карточек",
                verbose_name="Позиция в порядке следования карточек",
            ),
        ),
    ]
