# Generated by Django 4.1.1 on 2024-06-17 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0044_alter_courselanding_options_blockcards_position"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="courselanding",
            options={
                "verbose_name": "Блок с программой обучения",
                "verbose_name_plural": "Блоки с программой обучения",
            },
        ),
        migrations.RemoveField(
            model_name="blockcards",
            name="position",
        ),
    ]
