# Generated by Django 4.1.1 on 2024-06-17 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0044_alter_courselanding_options_blockcards_position"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="courselanding",
            name="audience",
        ),
        migrations.RemoveField(
            model_name="courselanding",
            name="course",
        ),
        migrations.RemoveField(
            model_name="courselanding",
            name="header",
        ),
        migrations.RemoveField(
            model_name="courselanding",
            name="stats",
        ),
        migrations.RemoveField(
            model_name="courselanding",
            name="training_program",
        ),
        migrations.DeleteModel(
            name="AudienceBlock",
        ),
        migrations.DeleteModel(
            name="BlockCards",
        ),
        migrations.DeleteModel(
            name="CourseLanding",
        ),
        migrations.DeleteModel(
            name="HeaderBlock",
        ),
        migrations.DeleteModel(
            name="StatsBlock",
        ),
        migrations.DeleteModel(
            name="TrainingProgram",
        ),
    ]
