# Generated by Django 4.1.1 on 2024-06-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0046_audienceblock_blockcards_headerblock_statsblock_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingpurpose",
            name="can_down",
            field=models.BooleanField(
                default=False,
                help_text="Упирается ли блок в нижний край списка",
                verbose_name="Можно сместить блок вниз",
            ),
        ),
        migrations.AddField(
            model_name="trainingpurpose",
            name="can_up",
            field=models.BooleanField(
                default=False,
                help_text="Упирается ли блок в верхний край списка",
                verbose_name="Можно сместить блок вверх",
            ),
        ),
        migrations.AddField(
            model_name="trainingpurpose",
            name="is_visible",
            field=models.BooleanField(
                default=True,
                help_text="Видимость в лендинге курса",
                verbose_name="Отображение блока",
            ),
        ),
        migrations.AddField(
            model_name="trainingpurpose",
            name="position",
            field=models.IntegerField(
                default=0,
                help_text="Номер следования в столбце блоков",
                verbose_name="Позиция в порядке следования блоков",
            ),
        ),
        migrations.AlterField(
            model_name="audienceblock",
            name="can_down",
            field=models.BooleanField(
                default=False,
                help_text="Упирается ли блок в нижний край списка",
                verbose_name="Можно сместить блок вниз",
            ),
        ),
        migrations.AlterField(
            model_name="audienceblock",
            name="can_up",
            field=models.BooleanField(
                default=False,
                help_text="Упирается ли блок в верхний край списка",
                verbose_name="Можно сместить блок вверх",
            ),
        ),
        migrations.AlterField(
            model_name="audienceblock",
            name="position",
            field=models.IntegerField(
                default=0,
                help_text="Номер следования в столбце блоков",
                verbose_name="Позиция в порядке следования блоков",
            ),
        ),
        migrations.AlterField(
            model_name="headerblock",
            name="can_down",
            field=models.BooleanField(
                default=False,
                help_text="Упирается ли блок в нижний край списка",
                verbose_name="Можно сместить блок вниз",
            ),
        ),
        migrations.AlterField(
            model_name="headerblock",
            name="can_up",
            field=models.BooleanField(
                default=False,
                help_text="Упирается ли блок в верхний край списка",
                verbose_name="Можно сместить блок вверх",
            ),
        ),
        migrations.AlterField(
            model_name="headerblock",
            name="position",
            field=models.IntegerField(
                default=0,
                help_text="Номер следования в столбце блоков",
                verbose_name="Позиция в порядке следования блоков",
            ),
        ),
        migrations.AlterField(
            model_name="statsblock",
            name="can_down",
            field=models.BooleanField(
                default=False,
                help_text="Упирается ли блок в нижний край списка",
                verbose_name="Можно сместить блок вниз",
            ),
        ),
        migrations.AlterField(
            model_name="statsblock",
            name="can_up",
            field=models.BooleanField(
                default=False,
                help_text="Упирается ли блок в верхний край списка",
                verbose_name="Можно сместить блок вверх",
            ),
        ),
        migrations.AlterField(
            model_name="statsblock",
            name="position",
            field=models.IntegerField(
                default=0,
                help_text="Номер следования в столбце блоков",
                verbose_name="Позиция в порядке следования блоков",
            ),
        ),
        migrations.AlterField(
            model_name="trainingprogram",
            name="can_down",
            field=models.BooleanField(
                default=False,
                help_text="Упирается ли блок в нижний край списка",
                verbose_name="Можно сместить блок вниз",
            ),
        ),
        migrations.AlterField(
            model_name="trainingprogram",
            name="can_up",
            field=models.BooleanField(
                default=False,
                help_text="Упирается ли блок в верхний край списка",
                verbose_name="Можно сместить блок вверх",
            ),
        ),
        migrations.AlterField(
            model_name="trainingprogram",
            name="position",
            field=models.IntegerField(
                default=0,
                help_text="Номер следования в столбце блоков",
                verbose_name="Позиция в порядке следования блоков",
            ),
        ),
    ]
