# Generated by Django 4.1.1 on 2024-06-18 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0045_alter_courselanding_options_and_more"),
        ("courses", "0047_trainingpurpose_can_down_trainingpurpose_can_up_and_more"),
    ]

    operations = []
