# Generated by Django 4.1.1 on 2024-06-18 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0048_merge_20240618_0833"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="courselanding",
            options={
                "verbose_name": "Блок с лендингом курса",
                "verbose_name_plural": "Блоки с лендингом курсов",
            },
        ),
        migrations.AddField(
            model_name="blockcards",
            name="position",
            field=models.IntegerField(
                default=0,
                help_text="Номер следования в списке карточек",
                verbose_name="Позиция в порядке следования карточек",
            ),
        ),
        migrations.AlterField(
            model_name="audienceblock",
            name="can_down",
            field=models.BooleanField(
                help_text="Упирается ли блок в нижний край списка",
                verbose_name="Можно сместить блок вниз",
            ),
        ),
        migrations.AlterField(
            model_name="audienceblock",
            name="can_up",
            field=models.BooleanField(
                help_text="Упирается ли блок в верхний край списка",
                verbose_name="Можно сместить блок вверх",
            ),
        ),
        migrations.AlterField(
            model_name="audienceblock",
            name="position",
            field=models.IntegerField(
                help_text="Номер следования в столбце блоков",
                verbose_name="Позиция в порядке следования блоков",
            ),
        ),
        migrations.AlterField(
            model_name="headerblock",
            name="can_down",
            field=models.BooleanField(
                help_text="Упирается ли блок в нижний край списка",
                verbose_name="Можно сместить блок вниз",
            ),
        ),
        migrations.AlterField(
            model_name="headerblock",
            name="can_up",
            field=models.BooleanField(
                help_text="Упирается ли блок в верхний край списка",
                verbose_name="Можно сместить блок вверх",
            ),
        ),
        migrations.AlterField(
            model_name="headerblock",
            name="position",
            field=models.IntegerField(
                help_text="Номер следования в столбце блоков",
                verbose_name="Позиция в порядке следования блоков",
            ),
        ),
        migrations.AlterField(
            model_name="statsblock",
            name="can_down",
            field=models.BooleanField(
                help_text="Упирается ли блок в нижний край списка",
                verbose_name="Можно сместить блок вниз",
            ),
        ),
        migrations.AlterField(
            model_name="statsblock",
            name="can_up",
            field=models.BooleanField(
                help_text="Упирается ли блок в верхний край списка",
                verbose_name="Можно сместить блок вверх",
            ),
        ),
        migrations.AlterField(
            model_name="statsblock",
            name="position",
            field=models.IntegerField(
                help_text="Номер следования в столбце блоков",
                verbose_name="Позиция в порядке следования блоков",
            ),
        ),
        migrations.AlterField(
            model_name="trainingprogram",
            name="can_down",
            field=models.BooleanField(
                help_text="Упирается ли блок в нижний край списка",
                verbose_name="Можно сместить блок вниз",
            ),
        ),
        migrations.AlterField(
            model_name="trainingprogram",
            name="can_up",
            field=models.BooleanField(
                help_text="Упирается ли блок в верхний край списка",
                verbose_name="Можно сместить блок вверх",
            ),
        ),
        migrations.AlterField(
            model_name="trainingprogram",
            name="position",
            field=models.IntegerField(
                help_text="Номер следования в столбце блоков",
                verbose_name="Позиция в порядке следования блоков",
            ),
        ),
        migrations.AlterField(
            model_name="trainingpurpose",
            name="can_down",
            field=models.BooleanField(
                help_text="Упирается ли блок в нижний край списка",
                verbose_name="Можно сместить блок вниз",
            ),
        ),
        migrations.AlterField(
            model_name="trainingpurpose",
            name="can_up",
            field=models.BooleanField(
                help_text="Упирается ли блок в верхний край списка",
                verbose_name="Можно сместить блок вверх",
            ),
        ),
        migrations.AlterField(
            model_name="trainingpurpose",
            name="position",
            field=models.IntegerField(
                help_text="Номер следования в столбце блоков",
                verbose_name="Позиция в порядке следования блоков",
            ),
        ),
    ]
