# Generated by Django 4.1.1 on 2024-06-25 08:02

from django.db import migrations


def update_students_table_info(apps, schema_editor):
    StudentsTableInfo = apps.get_model("courses", "StudentsTableInfo")
    default_info = [
        {"id": 1, "order": 1, "name": "Имя", "checked": True},
        {"id": 2, "order": 2, "name": "Email", "checked": True},
        {"id": 3, "order": 3, "name": "Суммарный балл", "checked": False},
        {"id": 4, "order": 4, "name": "Курс", "checked": False},
        {"id": 5, "order": 5, "name": "Дата регистрации", "checked": False},
        {"id": 6, "order": 6, "name": "Группа", "checked": False},
        {"id": 7, "order": 7, "name": "Средний балл", "checked": False},
        {"id": 8, "order": 8, "name": "Дата добавления в группу", "checked": False},
        {"id": 9, "order": 9, "name": "Дата удаления из группы", "checked": False},
        {"id": 10, "order": 10, "name": "Прогресс", "checked": False},
        {"id": 11, "order": 11, "name": "Номер телефона", "checked": False},
    ]

    for record in StudentsTableInfo.objects.all():
        current_info = {item["id"]: item for item in record.students_table_info}

        for item in default_info:
            if item["id"] not in current_info:
                current_info[item["id"]] = item

        record.students_table_info = sorted(
            current_info.values(), key=lambda x: x["id"]
        )
        record.save()


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0049_alter_courselanding_options_blockcards_position_and_more"),
    ]

    operations = [
        migrations.RunPython(update_students_table_info),
    ]
