# Generated by Django 4.1.1 on 2024-08-01 16:29

from django.db import migrations, transaction
from django.db.utils import IntegrityError

def create_courses_landing(apps, schema_editor):
    Course = apps.get_model('courses', 'Course')
    CourseLanding = apps.get_model('courses', 'CourseLanding')
    HeaderBlock = apps.get_model('courses', 'HeaderBlock')
    StatsBlock = apps.get_model('courses', 'StatsBlock')
    AudienceBlock = apps.get_model('courses', 'AudienceBlock')
    TrainingProgram = apps.get_model('courses', 'TrainingProgram')
    TrainingPurpose = apps.get_model('courses', 'TrainingPurpose')

    courses_without_landing = Course.objects.filter(course_school__isnull=True)

    for course in courses_without_landing:
        try:
            with transaction.atomic():
                CourseLanding.objects.create(
                    course=course,
                    header=HeaderBlock.objects.first(),
                    stats=StatsBlock.objects.first(),
                    audience=AudienceBlock.objects.first(),
                    training_program=TrainingProgram.objects.first(),
                    training_purpose=TrainingPurpose.objects.first()
                )
        except IntegrityError:
            print(f"Failed to create CourseLanding for course_id {course.id}")

class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0050_auto_20240625_0802"),
    ]

    operations = [migrations.RunPython(create_courses_landing)]
