# Generated by Django 4.1.1 on 2024-08-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0051_auto_20240801_1929"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="is_copy",
            field=models.BooleanField(
                default=False,
                help_text="Копия ли данный курс уже существующего",
                verbose_name="Копия ли данный курс уже существующего",
            ),
        ),
    ]
