# Generated by Django 4.1.1 on 2024-08-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0052_course_is_copy"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="is_access",
            field=models.BooleanField(
                default=True,
                help_text="Есть ли доступ к копии курса",
                verbose_name="Есть ли доступ к копии курса",
            ),
        ),
    ]
