# Generated by Django 4.1.1 on 2024-08-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0053_course_is_access"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="course_removed",
            field=models.DateTimeField(
                blank=True,
                help_text="Дата и время помещения курса в корзину",
                null=True,
                verbose_name="Дата и время помещения курса в корзину",
            ),
        ),
    ]
