# Generated by Django 4.1.1 on 2024-08-21 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0054_course_course_removed"),
    ]

    operations = [
        migrations.AddField(
            model_name="userhomework",
            name="copy_course_id",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="ID копии курса, если домашка относится к копии курса",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.course",
                verbose_name="ID копии курса",
            ),
        ),
    ]
