# Generated by Django 4.1.1 on 2024-08-28 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0055_userhomework_copy_course_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseCopy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course_id",
                    models.IntegerField(
                        blank=True,
                        help_text="ID курса оригинала",
                        null=True,
                        verbose_name="ID курса оригинала",
                    ),
                ),
                (
                    "course_copy_id",
                    models.ForeignKey(
                        help_text="ID курса копии",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.course",
                        verbose_name="ID курса копии",
                    ),
                ),
            ],
        ),
    ]
