# Generated by Django 4.1.1 on 2024-08-29 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0056_coursecopy"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="copy_course_id",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="ID копии курса, если коммент относится к копии курса",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.course",
                verbose_name="ID копии курса",
            ),
        ),
    ]
