# Generated by Django 4.1.1 on 2024-09-03 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0057_comment_copy_course_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="trainingduration",
            options={
                "verbose_name": "Продолжительность и иные особенности обучения",
                "verbose_name_plural": "Продолжительность и иные особенности обучения",
            },
        ),
        migrations.AddField(
            model_name="studentsgroupsettings",
            name="download",
            field=models.BooleanField(
                default=False,
                help_text="При 'True' - ученики данной группы могут скачивать видео-уроки",
                verbose_name="Возможность скачивания видео",
            ),
        ),
        migrations.AddField(
            model_name="trainingduration",
            name="download",
            field=models.BooleanField(
                default=False,
                help_text="При 'True' - ученик может скачивать видео-уроки в процессе обучения в данной группе",
                verbose_name="Возможность скачивания видео",
            ),
        ),
    ]
