# Generated by Django 4.1.1 on 2024-09-10 16:21

from django.db import migrations, models
import django.db.models.deletion

def create_default_link_button(apps, schema_editor):
    LinkButton = apps.get_model('courses', 'LinkButton')
    CourseLanding = apps.get_model('courses', 'CourseLanding')

    # Создание дефолтного объекта LinkButton
    default_link_button = LinkButton.objects.create(
        name='Кнопка',
        link='https://example.com',
        color='#BA75FF',
        position=5,
        can_up=True,
        can_down=False
    )

    # Обновление существующих записей в CourseLanding с дефолтным LinkButton
    CourseLanding.objects.all().update(link_button=default_link_button)

class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0058_alter_trainingduration_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LinkButton",
            fields=[
                (
                    "is_visible",
                    models.BooleanField(
                        default=True,
                        help_text="Видимость в лендинге курса",
                        verbose_name="Отображение блока",
                    ),
                ),
                (
                    "position",
                    models.IntegerField(
                        help_text="Номер следования в столбце блоков",
                        verbose_name="Позиция в порядке следования блоков",
                    ),
                ),
                (
                    "can_up",
                    models.BooleanField(
                        help_text="Упирается ли блок в верхний край списка",
                        verbose_name="Можно сместить блок вверх",
                    ),
                ),
                (
                    "can_down",
                    models.BooleanField(
                        help_text="Упирается ли блок в нижний край списка",
                        verbose_name="Можно сместить блок вниз",
                    ),
                ),
                (
                    "id",
                    models.AutoField(
                        editable=False,
                        help_text="Уникальный идентификатор блока цели обучения",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Текст кнопки",
                        max_length=200,
                        verbose_name="Текст кнопки",
                    ),
                ),
                (
                    "link",
                    models.URLField(
                        blank=True,
                        help_text="Ссылка для перехода по кнопке",
                        max_length=500,
                        null=True,
                        verbose_name="Ссылка",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        help_text="Цвет кнопки",
                        max_length=50,
                        null=True,
                        verbose_name="Цвет кнопки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Кнопка со ссылками для редактора лендинга",
                "verbose_name_plural": "Кнопки со ссылками для редактора лендинга",
            },
        ),
        migrations.AddField(
            model_name="courselanding",
            name="link_button",
            field=models.ForeignKey(
                help_text="Блок с ссылками",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="link_button",
                to="courses.linkbutton",
                verbose_name="Кнопка с ссылкой",
            ),
        ),
        migrations.RunPython(create_default_link_button),
    ]
