# Generated by Django 4.1.1 on 2024-10-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0059_linkbutton_courselanding_link_button"),
    ]

    operations = [
        migrations.AddField(
            model_name="baselessonblock",
            name="video_screenshot",
            field=models.TextField(
                blank=True,
                help_text="Превью видео",
                null=True,
                verbose_name="Превью видео",
            ),
        ),
    ]
