# Generated by Django 4.1.1 on 2024-10-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0060_baselessonblock_video_screenshot"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="baselesson",
            index=models.Index(
                fields=["section"], name="courses_bas_section_920458_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="baselesson",
            index=models.Index(fields=["name"], name="courses_bas_name_9e1c43_idx"),
        ),
        migrations.AddIndex(
            model_name="baselessonblock",
            index=models.Index(
                fields=["base_lesson"], name="courses_bas_base_le_d5ca4b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="baselessonblock",
            index=models.Index(
                fields=["description"], name="courses_bas_descrip_dac258_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="baselessonblock",
            index=models.Index(fields=["code"], name="courses_bas_code_4465f2_idx"),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["lesson"], name="courses_com_lesson__7f9bf7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["author"], name="courses_com_author__fe6bab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["created_at"], name="courses_com_created_482a57_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["school"], name="courses_cou_school__4249da_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(fields=["name"], name="courses_cou_name_eb4cc3_idx"),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["is_catalog"], name="courses_cou_is_cata_47580d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(fields=["public"], name="courses_cou_public_937d97_idx"),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["folder"], name="courses_cou_folder__0965ab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="courseappeals",
            index=models.Index(
                fields=["course"], name="courses_cou_course__0f0996_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="courseappeals",
            index=models.Index(fields=["email"], name="courses_cou_email_1921e8_idx"),
        ),
        migrations.AddIndex(
            model_name="courseappeals",
            index=models.Index(
                fields=["is_read"], name="courses_cou_is_read_98e356_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="folder",
            index=models.Index(
                fields=["school"], name="courses_fol_school__fd3919_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="folder",
            index=models.Index(fields=["name"], name="courses_fol_name_cb643e_idx"),
        ),
        migrations.AddIndex(
            model_name="groupcourseaccess",
            index=models.Index(
                fields=["current_group"], name="courses_gro_current_a593ae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="groupcourseaccess",
            index=models.Index(
                fields=["course"], name="courses_gro_course__911634_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="groupcourseaccess",
            index=models.Index(fields=["group"], name="courses_gro_group_i_5bed5c_idx"),
        ),
        migrations.AddIndex(
            model_name="lessonavailability",
            index=models.Index(
                fields=["student"], name="courses_les_student_8a0ab3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lessonavailability",
            index=models.Index(
                fields=["lesson"], name="courses_les_lesson__7122ba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lessonavailability",
            index=models.Index(
                fields=["available"], name="courses_les_availab_f58ed5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lessonenrollment",
            index=models.Index(
                fields=["student_group"], name="courses_les_student_9530d4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lessonenrollment",
            index=models.Index(
                fields=["lesson"], name="courses_les_lesson__918c3e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="section",
            index=models.Index(
                fields=["course"], name="courses_sec_course__46056e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="section",
            index=models.Index(fields=["name"], name="courses_sec_name_26dca0_idx"),
        ),
        migrations.AddIndex(
            model_name="studentsgroup",
            index=models.Index(fields=["name"], name="courses_stu_name_dae187_idx"),
        ),
        migrations.AddIndex(
            model_name="studentsgroup",
            index=models.Index(
                fields=["course_id"], name="courses_stu_course__b6a034_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentsgroup",
            index=models.Index(
                fields=["teacher_id"], name="courses_stu_teacher_f8cb3b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentsgroup",
            index=models.Index(
                fields=["group_id"], name="courses_stu_group_i_853aa4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentshistory",
            index=models.Index(fields=["user"], name="courses_stu_user_id_3963d6_idx"),
        ),
        migrations.AddIndex(
            model_name="studentshistory",
            index=models.Index(
                fields=["students_group"], name="courses_stu_student_05c20d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentshistory",
            index=models.Index(
                fields=["date_added"], name="courses_stu_date_ad_e75eb7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentshistory",
            index=models.Index(
                fields=["date_removed"], name="courses_stu_date_re_dfe9f4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trainingduration",
            index=models.Index(fields=["user"], name="courses_tra_user_id_8efbde_idx"),
        ),
        migrations.AddIndex(
            model_name="trainingduration",
            index=models.Index(
                fields=["students_group"], name="courses_tra_student_b18598_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userhomework",
            index=models.Index(fields=["user"], name="courses_use_user_id_621cb2_idx"),
        ),
        migrations.AddIndex(
            model_name="userhomework",
            index=models.Index(
                fields=["homework"], name="courses_use_homewor_13fe54_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userhomework",
            index=models.Index(
                fields=["teacher"], name="courses_use_teacher_648e13_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userhomework",
            index=models.Index(fields=["mark"], name="courses_use_mark_7b59db_idx"),
        ),
        migrations.AddIndex(
            model_name="userhomework",
            index=models.Index(fields=["status"], name="courses_use_status_ff096b_idx"),
        ),
        migrations.AddIndex(
            model_name="userhomeworkcheck",
            index=models.Index(
                fields=["user_homework"], name="courses_use_user_ho_5c838c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userhomeworkcheck",
            index=models.Index(fields=["status"], name="courses_use_status_b46450_idx"),
        ),
        migrations.AddIndex(
            model_name="userhomeworkcheck",
            index=models.Index(fields=["mark"], name="courses_use_mark_f2d5be_idx"),
        ),
        migrations.AddIndex(
            model_name="userprogresslogs",
            index=models.Index(fields=["user"], name="courses_use_user_id_9fda26_idx"),
        ),
        migrations.AddIndex(
            model_name="userprogresslogs",
            index=models.Index(
                fields=["lesson"], name="courses_use_lesson__1799de_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userprogresslogs",
            index=models.Index(fields=["viewed"], name="courses_use_viewed_ef5c3e_idx"),
        ),
        migrations.AddIndex(
            model_name="userprogresslogs",
            index=models.Index(
                fields=["completed"], name="courses_use_complet_601c61_idx"
            ),
        ),
    ]
