# Generated by Django 4.1.1 on 2024-10-23 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0061_baselesson_courses_bas_section_920458_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userhomework",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                help_text="Учитель, который проверял домашнюю работы",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher_homeworks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="ID учителя",
            ),
        ),
    ]
