# Generated by Django 4.1.1 on 2024-10-24 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0062_alter_userhomework_teacher"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentCourseProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "progress",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="courses.course"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="studentcourseprogress",
            index=models.Index(
                fields=["student", "course"], name="courses_stu_student_f3e6b2_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="studentcourseprogress",
            unique_together={("student", "course")},
        ),
    ]
