# Generated by Django 4.1.1 on 2024-10-31 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0063_studentcourseprogress_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="multiple_answer",
            field=models.BooleanField(
                default=False,
                help_text="Характерно для вопросов с множественным выбором ответов (TEXTPIC, TEXTPICS)",
                verbose_name="Множественный ответ",
            ),
        ),
        migrations.AddField(
            model_name="sectiontest",
            name="has_timer",
            field=models.BooleanField(
                default=False,
                help_text="Определяет, есть ли у теста ограничение по времени",
                verbose_name="Использовать таймер",
            ),
        ),
        migrations.AddField(
            model_name="sectiontest",
            name="time_limit",
            field=models.DurationField(
                blank=True,
                help_text="Продолжительность таймера для теста (например, 10 минут)",
                null=True,
                verbose_name="Лимит времени",
            ),
        ),
        migrations.AddField(
            model_name="usertest",
            name="start_time",
            field=models.DateTimeField(
                blank=True,
                help_text="Время, когда пользователь начал проходить тест",
                null=True,
                verbose_name="Время начала теста",
            ),
        ),
    ]
