# Generated by Django 4.1.1 on 2024-11-07 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0064_question_multiple_answer_sectiontest_has_timer_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="baselesson",
            name="unique_section_lesson_order",
        ),
    ]
