# Generated by Django 4.1.1 on 2024-11-19 08:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0065_remove_baselesson_unique_section_lesson_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingduration",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Дата и время, когда запись была создана",
                verbose_name="Создано",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="trainingduration",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Дата, когда запись была последний раз обновлена",
                verbose_name="Обновлено",
            ),
        ),
    ]
