# Generated by Django 4.1.1 on 2024-11-28 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0066_trainingduration_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="parent_comment",
            field=models.ForeignKey(
                blank=True,
                help_text="Комментарий, на который дается ответ",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="courses.comment",
                verbose_name="Родительский комментарий",
            ),
        ),
    ]
