# Generated by Django 4.2.16 on 2025-07-06 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0067_comment_parent_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessonavailability",
            name="access_time",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Время доступа к уроку в часах",
                null=True,
                verbose_name="Время доступа",
            ),
        ),
        migrations.AddField(
            model_name="lessonavailability",
            name="visible_timer",
            field=models.BooleanField(
                default=False,
                help_text="Показывать ли таймер доступа к уроку",
                verbose_name="Видимый таймер",
            ),
        ),
        migrations.AddIndex(
            model_name="lessonavailability",
            index=models.Index(
                fields=["visible_timer"], name="courses_les_visible_a39ce6_idx"
            ),
        ),
    ]
