# Generated by Django 4.0.6 on 2022-07-20 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=100)),
                ('doc', models.FileField(help_text='Договор ......', upload_to='documents', verbose_name='“Договор публичной оферты“')),
            ],
        ),
    ]
