# Generated by Django 4.0.6 on 2022-07-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=100)),
                ('doc', models.FileField(help_text='Документы ......', upload_to='documents', verbose_name='“Документы“')),
            ],
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
