from .answer import answer_schema
from .apply_auto_schema import apply_swagger_auto_schema
from .course import course_schema
from .homework import homework_schema
from .lesson import lesson_schema
from .question import question_schema
from .section import section_schema
from .section_test import section_test_schema
from .student_progress import StudentProgressSchemas
from .students_group import students_group_schema
from .students_group_settings import students_group_settings_schema
from .students_table_info import students_table_info_schema
from .user_homework_check import user_homework_check_schema
from .user_test import user_test_schema
