# Generated by Django 4.0.6 on 2022-07-13 19:12

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Дата и время, когда запись была создана', verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата, когда запись была последний раз обновлена', verbose_name='Обновлено')),
                ('answer_id', models.AutoField(editable=False, help_text='Уникальный идентификатор вопроса', primary_key=True, serialize=False, verbose_name='ID Вопроса')),
                ('body', ckeditor.fields.RichTextField(help_text='HTML вариант ответа', verbose_name='Тело ответа')),
                ('status', models.CharField(choices=[('П', 'Правильный'), ('Н', 'Неправильный')], default='П', help_text='Тип ответа: Правильный или неправильный или ещё какой', max_length=256, verbose_name='Тип ответа')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
        migrations.CreateModel(
            name='LessonTest',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Дата и время, когда запись была создана', verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата, когда запись была последний раз обновлена', verbose_name='Обновлено')),
                ('test_id', models.AutoField(editable=False, help_text='Уникальный идентификатор теста', primary_key=True, serialize=False, verbose_name='ID Теста')),
                ('name', models.CharField(help_text='Название теста', max_length=256, verbose_name='Название')),
                ('success_percent', models.IntegerField(help_text='Процент правильных ответов для успешно пройденного теста', verbose_name='Проходной балл')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесы',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Дата и время, когда запись была создана', verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата, когда запись была последний раз обновлена', verbose_name='Обновлено')),
                ('question_id', models.AutoField(editable=False, help_text='Уникальный идентификатор вопроса', primary_key=True, serialize=False, verbose_name='ID Вопроса')),
                ('body', ckeditor.fields.RichTextField(help_text='Тело вопроса', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='UserTest',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Дата и время, когда запись была создана', verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата, когда запись была последний раз обновлена', verbose_name='Обновлено')),
                ('user_test_id', models.AutoField(editable=False, help_text='Уникальный идентификатор сданнаго теста', primary_key=True, serialize=False, verbose_name='ID сданнаго теста')),
                ('success_percent', models.DecimalField(decimal_places=2, help_text='Процент правильных ответов, которые ввёл ученик ученик', max_digits=10, verbose_name='Процент(%) правильных ответов')),
                ('status', models.CharField(choices=[('П', 'Прошёл'), ('Н', 'Не прошёл')], default='П', help_text='Статус, отображающий, пройден ли тест учеником', max_length=256, verbose_name='Статус')),
                ('test_id', models.ForeignKey(help_text='Уникальный идентификатор теста', on_delete=django.db.models.deletion.CASCADE, related_name='user_test_test_id_fk', to='lesson_tests.lessontest', verbose_name='ID теста')),
            ],
            options={
                'verbose_name': 'Сданный тест',
                'verbose_name_plural': 'Сданные тесты',
            },
        ),
    ]
