# Generated by Django 4.0.6 on 2022-08-03 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_initial'),
        ('lesson_tests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usertest',
            name='user',
            field=models.ForeignKey(default=1, help_text='Уникальный идентификатор пользователя', on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='ID пользователя'),
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(help_text='Тест, к которому привязан вопрос', on_delete=django.db.models.deletion.CASCADE, related_name='question_test_id_fk', to='lesson_tests.lessontest', verbose_name='Тест'),
        ),
        migrations.AddField(
            model_name='lessontest',
            name='author_id',
            field=models.ForeignKey(help_text='Автор записи', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='lessontest',
            name='lesson_id',
            field=models.ForeignKey(help_text='Урок, после которого идёт данный тест', on_delete=django.db.models.deletion.CASCADE, related_name='lesson_test_id_fk', to='courses.lesson', verbose_name='ID урока'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(help_text='Вопрос, к которому привязан ответ', on_delete=django.db.models.deletion.CASCADE, related_name='question_answer_id_fk', to='lesson_tests.question', verbose_name='ID Вопроса'),
        ),
    ]
