# Generated by Django 4.0.6 on 2022-08-17 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_description_alter_course_duration_days_and_more'),
        ('lesson_tests', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessontest',
            name='lesson_id',
        ),
        migrations.AddField(
            model_name='lessontest',
            name='lesson',
            field=models.ForeignKey(default=21, help_text='Урок, после которого идёт данный тест', on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.lesson', verbose_name='ID урока'),
            preserve_default=False,
        ),
    ]
