# Generated by Django 4.0.6 on 2022-07-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_tests', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessontest',
            options={'verbose_name': 'Тест', 'verbose_name_plural': 'Тесты'},
        ),
        migrations.AddField(
            model_name='lessontest',
            name='random_answers',
            field=models.BooleanField(default=False, verbose_name='Перемешать ответы'),
        ),
        migrations.AddField(
            model_name='lessontest',
            name='random_questions',
            field=models.BooleanField(default=False, verbose_name='Перемешать вопросы'),
        ),
        migrations.AddField(
            model_name='lessontest',
            name='show_right_answers',
            field=models.BooleanField(default=False, verbose_name='Показать правильные ответы'),
        ),
        migrations.AlterField(
            model_name='lessontest',
            name='test_id',
            field=models.AutoField(editable=False, help_text='Уникальный идентификатор теста', primary_key=True, serialize=False, verbose_name='ID теста'),
        ),
        migrations.AlterField(
            model_name='usertest',
            name='status',
            field=models.CharField(choices=[('П', 'Прошёл'), ('Н', 'Не прошёл')], default='П', help_text='Статус, отображающий пройден ли тест учеником', max_length=256, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='usertest',
            name='user_test_id',
            field=models.AutoField(editable=False, help_text='Уникальный идентификатор сданного теста', primary_key=True, serialize=False, verbose_name='ID сданного теста'),
        ),
    ]
