# Generated by Django 4.0.6 on 2022-07-13 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Дата и время, когда запись была создана', verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата, когда запись была последний раз обновлена', verbose_name='Обновлено')),
                ('chat_id', models.AutoField(editable=False, help_text='Уникальный идентификатор чата', primary_key=True, serialize=False, verbose_name='ID чата')),
            ],
            options={
                'verbose_name': 'Чат',
                'verbose_name_plural': 'Чаты',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Дата и время, когда запись была создана', verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата, когда запись была последний раз обновлена', verbose_name='Обновлено')),
                ('message_id', models.AutoField(editable=False, help_text='Уникальный идентификатор сообщения', primary_key=True, serialize=False, verbose_name='ID сообщения')),
                ('text', models.TextField(help_text='Сообщение, которое было отправлено пользователем', max_length=500, verbose_name='Сообщение')),
                ('chat', models.ForeignKey(help_text='Чат, в котором было отправлено это сообщение', on_delete=django.db.models.deletion.CASCADE, related_name='message_chat_id_fk', to='chat.chat', verbose_name='ID чата')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
    ]
