# Generated by Django 4.0.6 on 2022-08-03 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(default=1, help_text='Пользователь, отправивший сообщение', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='chat',
            name='admin',
            field=models.ForeignKey(default=1, help_text='Пользователь, являющийся админом чата, по умолчанию - супер админ', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='Админ'),
        ),
        migrations.AddField(
            model_name='chat',
            name='participants',
            field=models.ManyToManyField(related_name='user_chat_mtm', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи'),
        ),
    ]
