# Generated by Django 4.1.1 on 2023-10-05 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="ID владельца школы",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owner_school",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец школы",
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="tariff",
            field=models.ForeignKey(
                blank=True,
                help_text="Тариф школы",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="schools.tariff",
                verbose_name="Тариф",
            ),
        ),
        migrations.AddConstraint(
            model_name="school",
            constraint=models.UniqueConstraint(
                fields=("order",), name="unique_school_order"
            ),
        ),
    ]
