# Generated by Django 5.2.5 on 2025-08-11 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='banneraccept',
            name='user',
            field=models.ForeignKey(help_text='Пользователь', on_delete=django.db.models.deletion.CASCADE, related_name='banner_accepts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='bannerclick',
            name='banner',
            field=models.ForeignKey(help_text='Баннер', on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='schools.banner', verbose_name='Баннер'),
        ),
        migrations.AddField(
            model_name='bannerclick',
            name='user',
            field=models.ForeignKey(help_text='Пользователь', on_delete=django.db.models.deletion.CASCADE, related_name='banner_clicks', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='bonus',
            name='student_groups',
            field=models.ManyToManyField(blank=True, help_text='Группы, которым предоставлен бонус', related_name='group_bonuses', to='courses.studentsgroup', verbose_name='Группы'),
        ),
        migrations.AddField(
            model_name='boxprize',
            name='box',
            field=models.ForeignKey(help_text='Коробка', on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='schools.box', verbose_name='Коробка'),
        ),
        migrations.AddField(
            model_name='inviteprogram',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='invite_program', to='courses.studentsgroup', verbose_name='Группы'),
        ),
        migrations.AddIndex(
            model_name='newslettertemplate',
            index=models.Index(fields=['template_name'], name='schools_new_templat_8b17b7_idx'),
        ),
        migrations.AddField(
            model_name='payment',
            name='box',
            field=models.ForeignKey(help_text='Коробка', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='schools.box', verbose_name='Коробка'),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(help_text='Пользователь', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='boxprize',
            name='prize',
            field=models.ForeignKey(help_text='Приз', on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='schools.prize', verbose_name='Приз'),
        ),
        migrations.AddIndex(
            model_name='promocode',
            index=models.Index(fields=['name'], name='schools_pro_name_f137e6_idx'),
        ),
        migrations.AddField(
            model_name='school',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='ID владельца школы', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_school', to=settings.AUTH_USER_MODEL, verbose_name='Владелец школы'),
        ),
        migrations.AddField(
            model_name='referralclick',
            name='school',
            field=models.ForeignKey(help_text='Школа, чей реферальный код был использован', on_delete=django.db.models.deletion.CASCADE, related_name='referral_clicks', to='schools.school', verbose_name='Школа'),
        ),
        migrations.AddField(
            model_name='referral',
            name='referred_school',
            field=models.OneToOneField(help_text='Привлеченная школа', on_delete=django.db.models.deletion.CASCADE, related_name='referred_by', to='schools.school', verbose_name='Привлеченная школа'),
        ),
        migrations.AddField(
            model_name='referral',
            name='referrer_school',
            field=models.ForeignKey(help_text='Школа-реферер', on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='schools.school', verbose_name='Школа-реферер'),
        ),
        migrations.AddField(
            model_name='prodamuspaymentlink',
            name='school',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='schools.school'),
        ),
        migrations.AddField(
            model_name='prize',
            name='school',
            field=models.ForeignKey(help_text='ID школы', on_delete=django.db.models.deletion.CASCADE, related_name='prizes_school', to='schools.school', verbose_name='ID школы'),
        ),
        migrations.AddField(
            model_name='payment',
            name='school',
            field=models.ForeignKey(help_text='ID школы', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='schools.school', verbose_name='ID школы'),
        ),
        migrations.AddField(
            model_name='inviteprogram',
            name='school',
            field=models.ForeignKey(help_text='инвайт-программa', on_delete=django.db.models.deletion.CASCADE, related_name='invite_program', to='schools.school', verbose_name='инвайт-программa'),
        ),
        migrations.AddField(
            model_name='domain',
            name='school',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='domain', to='schools.school'),
        ),
        migrations.AddField(
            model_name='box',
            name='school',
            field=models.ForeignKey(help_text='ID школы', on_delete=django.db.models.deletion.CASCADE, related_name='boxes_school', to='schools.school', verbose_name='ID школы'),
        ),
        migrations.AddField(
            model_name='bonus',
            name='school',
            field=models.ForeignKey(help_text='ID школы', on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='schools.school', verbose_name='ID школы'),
        ),
        migrations.AddField(
            model_name='banner',
            name='school',
            field=models.ForeignKey(help_text='Баннер школы', on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='schools.school', verbose_name='Баннер школы'),
        ),
        migrations.AddField(
            model_name='schoolbranding',
            name='school',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branding', to='schools.school'),
        ),
        migrations.AddField(
            model_name='schooldocuments',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school'),
        ),
        migrations.AddField(
            model_name='schooldocuments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schoolexpresspaylink',
            name='school',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='schools.school'),
        ),
        migrations.AddField(
            model_name='schoolheader',
            name='school',
            field=models.OneToOneField(help_text='ID школы,которой принадлежит школа', on_delete=django.db.models.deletion.CASCADE, related_name='header_school', to='schools.school', verbose_name='ID школы'),
        ),
        migrations.AddField(
            model_name='schoolmeetings',
            name='students_groups',
            field=models.ManyToManyField(related_name='school_meetings', to='courses.studentsgroup'),
        ),
        migrations.AddField(
            model_name='schoolnewrole',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school', verbose_name='Школа, в которой выдается доступ на новую роль'),
        ),
        migrations.AddField(
            model_name='schoolnewrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, которому выдается доступ на новую роль'),
        ),
        migrations.AddField(
            model_name='schoolpaymentmethod',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school'),
        ),
        migrations.AddField(
            model_name='schoolexpresspaylink',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.schoolpaymentmethod'),
        ),
        migrations.AddField(
            model_name='prodamuspaymentlink',
            name='school_payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.schoolpaymentmethod'),
        ),
        migrations.AddField(
            model_name='schoolstatistics',
            name='school',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='schools.school', verbose_name='Школа'),
        ),
        migrations.AddField(
            model_name='schoolstudentstablesettings',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school'),
        ),
        migrations.AddField(
            model_name='schooltask',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='schools.school', verbose_name='Школа'),
        ),
        migrations.AddField(
            model_name='sentnewsletter',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_newsletters', to='schools.school', verbose_name='Школа'),
        ),
        migrations.AddField(
            model_name='sentnewsletter',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_newsletters', to='schools.newslettertemplate', verbose_name='Шаблон рассылки'),
        ),
        migrations.AddIndex(
            model_name='tariff',
            index=models.Index(fields=['name'], name='schools_tar_name_8e5059_idx'),
        ),
        migrations.AddField(
            model_name='school',
            name='tariff',
            field=models.ForeignKey(blank=True, help_text='Тариф школы', null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.tariff', verbose_name='Тариф'),
        ),
        migrations.AddField(
            model_name='userbox',
            name='box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_boxes', to='schools.box', verbose_name='Коробка'),
        ),
        migrations.AddField(
            model_name='userbox',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_boxes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='userprize',
            name='prize',
            field=models.ForeignKey(help_text='Приз', on_delete=django.db.models.deletion.CASCADE, related_name='user_prizes', to='schools.prize', verbose_name='Приз'),
        ),
        migrations.AddField(
            model_name='userprize',
            name='user',
            field=models.ForeignKey(help_text='Пользователь', on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddIndex(
            model_name='banneraccept',
            index=models.Index(fields=['banner', 'user'], name='schools_ban_banner__88cb0d_idx'),
        ),
        migrations.AddIndex(
            model_name='bannerclick',
            index=models.Index(fields=['timestamp'], name='schools_ban_timesta_b1109d_idx'),
        ),
        migrations.AddIndex(
            model_name='referralclick',
            index=models.Index(fields=['school'], name='schools_ref_school__834705_idx'),
        ),
        migrations.AddIndex(
            model_name='referralclick',
            index=models.Index(fields=['timestamp'], name='schools_ref_timesta_097f3d_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['referrer_school'], name='schools_ref_referre_2fca4e_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['referred_school'], name='schools_ref_referre_bbcbd9_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['created_at'], name='schools_ref_created_bea952_idx'),
        ),
        migrations.AddIndex(
            model_name='inviteprogram',
            index=models.Index(fields=['is_active'], name='schools_inv_is_acti_047583_idx'),
        ),
        migrations.AddIndex(
            model_name='inviteprogram',
            index=models.Index(fields=['school'], name='schools_inv_school__934935_idx'),
        ),
        migrations.AddIndex(
            model_name='domain',
            index=models.Index(fields=['domain_name'], name='schools_dom_domain__f61059_idx'),
        ),
        migrations.AddIndex(
            model_name='domain',
            index=models.Index(fields=['nginx_configured'], name='schools_dom_nginx_c_3f065b_idx'),
        ),
        migrations.AddIndex(
            model_name='domain',
            index=models.Index(fields=['school'], name='schools_dom_school__396036_idx'),
        ),
        migrations.AddIndex(
            model_name='bonus',
            index=models.Index(fields=['search_vector'], name='schools_bon_search__44474f_idx'),
        ),
        migrations.AddIndex(
            model_name='bonus',
            index=models.Index(fields=['school'], name='schools_bon_school__1c56c0_idx'),
        ),
        migrations.AddIndex(
            model_name='bonus',
            index=models.Index(fields=['expire_date'], name='schools_bon_expire__0e14c0_idx'),
        ),
        migrations.AddIndex(
            model_name='bonus',
            index=models.Index(fields=['active'], name='schools_bon_active_99ac64_idx'),
        ),
        migrations.AddIndex(
            model_name='banner',
            index=models.Index(fields=['is_active'], name='schools_ban_is_acti_94a53d_idx'),
        ),
        migrations.AddIndex(
            model_name='banner',
            index=models.Index(fields=['school'], name='schools_ban_school__f43c6a_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolbranding',
            index=models.Index(fields=['school'], name='schools_sch_school__e16933_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolbranding',
            index=models.Index(fields=['email'], name='schools_sch_email_90eafe_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolbranding',
            index=models.Index(fields=['phone'], name='schools_sch_phone_a4da2f_idx'),
        ),
        migrations.AddIndex(
            model_name='schooldocuments',
            index=models.Index(fields=['user'], name='schools_sch_user_id_f8c55b_idx'),
        ),
        migrations.AddIndex(
            model_name='schooldocuments',
            index=models.Index(fields=['school'], name='schools_sch_school__05dc0b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='schooldocuments',
            unique_together={('user', 'school')},
        ),
        migrations.AddIndex(
            model_name='schoolheader',
            index=models.Index(fields=['name'], name='schools_sch_name_4a363f_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolheader',
            index=models.Index(fields=['school'], name='schools_sch_school__6db61a_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolmeetings',
            index=models.Index(fields=['start_date'], name='schools_sch_start_d_09df30_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolnewrole',
            index=models.Index(fields=['school'], name='schools_sch_school__910b5b_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolnewrole',
            index=models.Index(fields=['user'], name='schools_sch_user_id_961be3_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolnewrole',
            index=models.Index(fields=['role_name'], name='schools_sch_role_na_9f57a7_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolstatistics',
            index=models.Index(fields=['school'], name='schools_sch_school__90c6ee_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='schooltask',
            unique_together={('school', 'task')},
        ),
        migrations.AddIndex(
            model_name='sentnewsletter',
            index=models.Index(fields=['school'], name='schools_sen_school__7080af_idx'),
        ),
        migrations.AddIndex(
            model_name='sentnewsletter',
            index=models.Index(fields=['template'], name='schools_sen_templat_bf75fd_idx'),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['name'], name='schools_sch_name_5d0cfd_idx'),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['tariff'], name='schools_sch_tariff__069195_idx'),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['owner'], name='schools_sch_owner_i_bd0dc7_idx'),
        ),
        migrations.AddConstraint(
            model_name='school',
            constraint=models.UniqueConstraint(fields=('order',), name='unique_school_order'),
        ),
    ]
