# Generated by Django 4.1.1 on 2023-10-05 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0002_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PromoCode",
        ),
    ]
