# Generated by Django 4.1.1 on 2023-10-05 10:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0003_promocode"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="promocode",
            options={"verbose_name": "Промокод", "verbose_name_plural": "Промокоды"},
        ),
        migrations.AlterModelOptions(
            name="tariff",
            options={"verbose_name": "Тариф", "verbose_name_plural": "Тарифы"},
        ),
        migrations.RemoveField(
            model_name="school",
            name="avatar",
        ),
        migrations.RemoveField(
            model_name="schoolheader",
            name="favicon",
        ),
        migrations.RemoveField(
            model_name="schoolheader",
            name="logo_header",
        ),
        migrations.AddField(
            model_name="promocode",
            name="uses_count",
            field=models.PositiveIntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(0)]
            ),
            preserve_default=False,
        ),
    ]
