# Generated by Django 4.1.1 on 2023-11-23 11:09

import common_services.services.file_validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0004_promocode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schoolheader",
            name="logo_school",
            field=models.ImageField(
                blank=True,
                help_text="Фотография заголовка школы",
                max_length=300,
                null=True,
                upload_to="",
                validators=[common_services.services.file_validation.limit_size],
                verbose_name="Фотография",
            ),
        ),
        migrations.AlterField(
            model_name="schoolheader",
            name="photo_background",
            field=models.ImageField(
                blank=True,
                help_text="Фотография фона",
                max_length=300,
                null=True,
                upload_to="",
                validators=[common_services.services.file_validation.limit_size],
                verbose_name="Фотография",
            ),
        ),
    ]
