# Generated by Django 4.1.1 on 2024-01-07 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0006_alter_schoolheader_logo_school_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(verbose_name="Начальная дата статистики"),
                ),
                ("end_date", models.DateField(verbose_name="Конечная дата статистики")),
                (
                    "school",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statistics",
                        to="schools.school",
                        verbose_name="Школа",
                    ),
                ),
            ],
            options={
                "verbose_name": "Статистика школы",
                "verbose_name_plural": "Статистика школ",
            },
        ),
    ]
