# Generated by Django 4.1.1 on 2024-02-07 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0007_schoolstatistics"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schoolstatistics",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="schoolstatistics",
            name="start_date",
        ),
    ]
