# Generated by Django 4.1.1 on 2024-02-21 09:58

import common_services.services.file_validation
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("schools", "0008_remove_schoolstatistics_end_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolDocuments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stamp",
                    models.FileField(
                        blank=True,
                        help_text="Печать школы",
                        max_length=300,
                        null=True,
                        upload_to=common_services.services.file_validation.TruncateFileName(
                            300
                        ),
                        validators=[
                            common_services.services.file_validation.limit_size
                        ],
                        verbose_name="Печать школы",
                    ),
                ),
                (
                    "signature",
                    models.FileField(
                        blank=True,
                        help_text="Подпись школы",
                        max_length=300,
                        null=True,
                        upload_to=common_services.services.file_validation.TruncateFileName(
                            300
                        ),
                        validators=[
                            common_services.services.file_validation.limit_size
                        ],
                        verbose_name="Подпись школы",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="schools.school"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Документы школы",
                "verbose_name_plural": "Документы школ",
                "unique_together": {("user", "school")},
            },
        ),
    ]
