# Generated by Django 4.1.1 on 2024-03-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0009_schooldocuments"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="contact_link",
            field=models.URLField(
                blank=True,
                help_text="Ссылка для связи с организатором курса по вопросам записи",
                null=True,
                verbose_name="Ссылка для связи",
            ),
        ),
    ]
