# Generated by Django 4.1.1 on 2024-03-18 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0010_school_contact_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tariff",
            name="name",
            field=models.CharField(
                choices=[
                    ("Junior", "Junior"),
                    ("Middle", "Middle"),
                    ("Senior", "Senior"),
                ],
                default="Junior",
                max_length=10,
            ),
        ),
    ]
