# Generated by Django 4.1.1 on 2024-03-24 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0011_alter_tariff_name"),
    ]

    operations = []
