# Generated by Django 4.1.1 on 2024-03-24 14:40

import common_services.services.file_validation
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0012_auto_20240324_1740"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schooldocuments",
            name="signature",
            field=models.FileField(
                blank=True,
                help_text="Подпись школы",
                max_length=300,
                null=True,
                upload_to=common_services.services.file_validation.TruncateFileName(
                    300
                ),
                validators=[common_services.services.file_validation.limit_image_size],
                verbose_name="Подпись школы",
            ),
        ),
        migrations.AlterField(
            model_name="schooldocuments",
            name="stamp",
            field=models.FileField(
                blank=True,
                help_text="Печать школы",
                max_length=300,
                null=True,
                upload_to=common_services.services.file_validation.TruncateFileName(
                    300
                ),
                validators=[common_services.services.file_validation.limit_image_size],
                verbose_name="Печать школы",
            ),
        ),
        migrations.AlterField(
            model_name="schoolheader",
            name="logo_school",
            field=models.ImageField(
                blank=True,
                help_text="Фотография заголовка школы",
                max_length=300,
                null=True,
                upload_to=common_services.services.file_validation.TruncateFileName(
                    300
                ),
                validators=[common_services.services.file_validation.limit_image_size],
                verbose_name="Фотография",
            ),
        ),
        migrations.AlterField(
            model_name="schoolheader",
            name="photo_background",
            field=models.ImageField(
                blank=True,
                help_text="Фотография фона",
                max_length=300,
                null=True,
                upload_to=common_services.services.file_validation.TruncateFileName(
                    300
                ),
                validators=[common_services.services.file_validation.limit_image_size],
                verbose_name="Фотография",
            ),
        ),
        migrations.CreateModel(
            name="SchoolPaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_method_name", models.CharField(max_length=100)),
                ("payment_link", models.CharField(max_length=400)),
                ("secret_key", models.CharField(max_length=100)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="schools.school"
                    ),
                ),
            ],
            options={
                "verbose_name": "Оплата курсов для школы",
                "verbose_name_plural": "Оплата курсов для школ",
            },
        ),
    ]
