# Generated by Django 4.1.1 on 2024-03-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0013_alter_schooldocuments_signature_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolpaymentmethod",
            name="payment_method",
            field=models.CharField(
                default=None,
                help_text="Метод оплаты",
                max_length=25,
                verbose_name="Метод оплаты",
            ),
        ),
        migrations.AlterField(
            model_name="schoolpaymentmethod",
            name="payment_link",
            field=models.CharField(
                help_text="Ссылка на страницу для оплаты",
                max_length=400,
                verbose_name="Ссылка",
            ),
        ),
        migrations.AlterField(
            model_name="schoolpaymentmethod",
            name="payment_method_name",
            field=models.CharField(
                help_text="Название метода оплаты",
                max_length=100,
                verbose_name="Название метода оплаты",
            ),
        ),
        migrations.AlterField(
            model_name="schoolpaymentmethod",
            name="secret_key",
            field=models.CharField(
                help_text="Секретный ключ",
                max_length=100,
                verbose_name="Секретный ключ",
            ),
        ),
    ]
