# Generated by Django 4.1.1 on 2024-03-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0014_schoolpaymentmethod_payment_method_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schoolpaymentmethod",
            name="payment_link",
            field=models.CharField(
                help_text="Ссылка на страницу для оплаты",
                max_length=400,
                unique=True,
                verbose_name="Ссылка",
            ),
        ),
    ]
