# Generated by Django 4.1.1 on 2024-04-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0015_alter_schoolpaymentmethod_payment_link"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="schoolpaymentmethod",
            options={"verbose_name": "Оплата", "verbose_name_plural": "Оплата"},
        ),
        migrations.RemoveField(
            model_name="schoolpaymentmethod",
            name="payment_link",
        ),
        migrations.RemoveField(
            model_name="schoolpaymentmethod",
            name="secret_key",
        ),
        migrations.AddField(
            model_name="schoolpaymentmethod",
            name="account_no",
            field=models.CharField(
                default=None,
                help_text="Номер лицевого счета",
                max_length=200,
                unique=True,
                verbose_name="Номер лицевого счета",
            ),
        ),
        migrations.AddField(
            model_name="schoolpaymentmethod",
            name="api_key",
            field=models.CharField(
                default=None,
                help_text="API-ключ",
                max_length=200,
                unique=True,
                verbose_name="API-ключ",
            ),
        ),
        migrations.AlterField(
            model_name="schoolpaymentmethod",
            name="payment_method_name",
            field=models.CharField(
                default=None,
                help_text="Название метода оплаты",
                max_length=100,
                verbose_name="Название метода оплаты",
            ),
        ),
    ]
