# Generated by Django 4.1.1 on 2024-04-10 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0016_alter_schoolpaymentmethod_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolPaymentLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_no",
                    models.IntegerField(
                        default=0, help_text="Номер счета", verbose_name="Номер счета"
                    ),
                ),
                (
                    "payment_link",
                    models.CharField(
                        default=None,
                        help_text="Ссылка для оплаты",
                        max_length=200,
                        verbose_name="Ссылка для оплаты",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default=None,
                        help_text="Статус оплаты",
                        max_length=50,
                        verbose_name="Статус оплаты",
                    ),
                ),
                (
                    "created",
                    models.CharField(
                        default=None,
                        help_text="Время создания ссылки",
                        max_length=60,
                        verbose_name="Время создания ссылки",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Сумма оплаты",
                        max_digits=15,
                        verbose_name="Сумма оплаты",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default=None,
                        help_text="Код валюты",
                        max_length=3,
                        verbose_name="Код валюты",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        default=None,
                        help_text="Имя плательщика",
                        max_length=60,
                        verbose_name="Имя плательщика",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        default=None,
                        help_text="Фамилия плательщика",
                        max_length=60,
                        verbose_name="Фамилия плательщика",
                    ),
                ),
                (
                    "patronymic",
                    models.CharField(
                        default=None,
                        help_text="Отчество плательщика",
                        max_length=60,
                        verbose_name="Отчество плательщика",
                    ),
                ),
                (
                    "payment_method",
                    models.ForeignKey(
                        help_text="Метод оплаты",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schools.schoolpaymentmethod",
                        verbose_name="Метод оплаты",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ссылка на оплату",
                "verbose_name_plural": "Ссылки на оплату",
            },
        ),
    ]
