# Generated by Django 4.1.1 on 2024-04-10 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0017_schoolpaymentlink"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolpaymentlink",
            name="school",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="schools.school",
            ),
        ),
        migrations.AlterField(
            model_name="schoolpaymentlink",
            name="payment_method",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="schools.schoolpaymentmethod",
            ),
        ),
    ]
