# Generated by Django 4.1.1 on 2024-04-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0018_schoolpaymentlink_school_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schoolpaymentlink",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Время создания ссылки",
                verbose_name="Время создания ссылки",
            ),
        ),
        migrations.AlterField(
            model_name="schoolpaymentlink",
            name="status",
            field=models.CharField(
                default=None,
                help_text="Статус оплаты",
                max_length=50,
                null=True,
                verbose_name="Статус оплаты",
            ),
        ),
    ]
