# Generated by Django 4.1.1 on 2024-04-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0019_alter_schoolpaymentlink_created_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schoolpaymentlink",
            name="currency",
            field=models.CharField(
                default=None,
                help_text="Код валюты",
                max_length=3,
                null=True,
                verbose_name="Код валюты",
            ),
        ),
        migrations.AlterField(
            model_name="schoolpaymentlink",
            name="first_name",
            field=models.CharField(
                default=None,
                help_text="Имя плательщика",
                max_length=60,
                null=True,
                verbose_name="Имя плательщика",
            ),
        ),
        migrations.AlterField(
            model_name="schoolpaymentlink",
            name="last_name",
            field=models.CharField(
                default=None,
                help_text="Фамилия плательщика",
                max_length=60,
                null=True,
                verbose_name="Фамилия плательщика",
            ),
        ),
        migrations.AlterField(
            model_name="schoolpaymentlink",
            name="patronymic",
            field=models.CharField(
                default=None,
                help_text="Отчество плательщика",
                max_length=60,
                null=True,
                verbose_name="Отчество плательщика",
            ),
        ),
    ]
