# Generated by Django 4.1.1 on 2024-04-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0020_alter_schoolpaymentlink_currency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolpaymentlink",
            name="api_key",
            field=models.CharField(
                default=None,
                help_text="API-ключ",
                max_length=200,
                unique=True,
                verbose_name="API-ключ",
            ),
        ),
    ]
