# Generated by Django 4.1.1 on 2024-04-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0021_schoolpaymentlink_api_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schoolpaymentlink",
            name="api_key",
            field=models.CharField(
                default=None,
                help_text="API-ключ",
                max_length=200,
                verbose_name="API-ключ",
            ),
        ),
    ]
