# Generated by Django 4.1.1 on 2024-04-21 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0022_alter_schoolpaymentlink_api_key"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SchoolPaymentLink",
            new_name="SchoolExpressPayLink",
        ),
    ]
