# Generated by Django 4.1.1 on 2024-04-28 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0022_alter_schoolpaymentlink_api_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolpaymentmethod",
            name="payment_url",
            field=models.URLField(
                default=None,
                help_text="Ссылка платежного кабинета Продамус",
                max_length=250,
                null=True,
                verbose_name="URL платежного кабинета",
            ),
        ),
        migrations.AlterField(
            model_name="schoolpaymentlink",
            name="invoice_no",
            field=models.IntegerField(
                default=0,
                help_text="Номер счета",
                null=True,
                verbose_name="Номер счета",
            ),
        ),
        migrations.AlterField(
            model_name="schoolpaymentmethod",
            name="account_no",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Номер лицевого счета",
                max_length=200,
                null=True,
                unique=True,
                verbose_name="Номер лицевого счета",
            ),
        ),
        migrations.AlterField(
            model_name="schoolpaymentmethod",
            name="payment_method",
            field=models.CharField(
                default=None,
                help_text="Метод оплаты",
                max_length=25,
                null=True,
                verbose_name="Метод оплаты",
            ),
        ),
        migrations.CreateModel(
            name="ProdamusPaymentLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Время создания ссылки",
                        verbose_name="Время создания ссылки",
                    ),
                ),
                (
                    "payment_link",
                    models.CharField(
                        blank=True,
                        help_text="Ссылка для оплаты",
                        max_length=700,
                        null=True,
                        verbose_name="Сформированная ссылка для оплаты",
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        default="",
                        help_text="API-ключ",
                        max_length=200,
                        verbose_name="API-ключ",
                    ),
                ),
                (
                    "do",
                    models.CharField(
                        help_text="Тип действий (link или pay)", max_length=20
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default=None,
                        help_text="Наименование товара",
                        max_length=200,
                        verbose_name="Наименование товара",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, help_text="Цена товара", max_digits=10
                    ),
                ),
                ("quantity", models.PositiveIntegerField(help_text="Кол-во товара")),
                (
                    "sys",
                    models.CharField(
                        blank=True,
                        help_text="код системы интернет-магазина",
                        max_length=100,
                        null=True,
                        verbose_name="код системы интернет-магазина",
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        blank=True,
                        help_text="ID товара в системе интернет-магазин",
                        max_length=200,
                        null=True,
                        verbose_name="ID товара в системе интернет-магазин",
                    ),
                ),
                (
                    "order_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Номер заказа в системе интернет-магазина",
                        null=True,
                    ),
                ),
                (
                    "customer_phone",
                    models.CharField(
                        blank=True,
                        help_text="Можно сформировать ссылку на оплату не указывая номер телефона покупателя, он заполнит это поле самостоятельно в окне оплаты",
                        max_length=20,
                        null=True,
                        verbose_name="Мобильный телефон клиента",
                    ),
                ),
                (
                    "customer_email",
                    models.EmailField(
                        blank=True, help_text="Email клиента", max_length=254, null=True
                    ),
                ),
                (
                    "customer_extra",
                    models.TextField(
                        blank=True, help_text="Дополнительные данные", null=True
                    ),
                ),
                (
                    "tax_type",
                    models.PositiveIntegerField(default=0, help_text="Ставка НДС"),
                ),
                (
                    "tax_sum",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Сумма налога",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True, help_text="Метод оплаты", max_length=2, null=True
                    ),
                ),
                (
                    "payment_object",
                    models.CharField(
                        blank=True, help_text="Тип оплачиваемой позиции", max_length=2
                    ),
                ),
                (
                    "subscription",
                    models.PositiveIntegerField(
                        blank=True, help_text="ID подписки", null=True
                    ),
                ),
                (
                    "subscription_date_start",
                    models.DateTimeField(
                        blank=True, help_text="Дата начала подписки", null=True
                    ),
                ),
                (
                    "vk_user_id",
                    models.PositiveIntegerField(
                        blank=True, help_text="ID пользователя VK", null=True
                    ),
                ),
                (
                    "vk_user_name",
                    models.CharField(
                        blank=True,
                        help_text="Имя пользователя VK",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "urlReturn",
                    models.URLField(
                        blank=True,
                        help_text="URL для возврата пользователя без оплаты",
                        null=True,
                    ),
                ),
                (
                    "urlSuccess",
                    models.URLField(
                        blank=True,
                        help_text="URL для возврата пользователя при успешной оплате",
                        null=True,
                    ),
                ),
                (
                    "urlNotification",
                    models.URLField(
                        blank=True,
                        help_text="URL для уведомления интернет-магазина о поступлении оплаты по заказу. Для того, чтобы система учла этот параметр, также должен быть передан параметр sys",
                        null=True,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Сумма скидки на заказ",
                        max_digits=10,
                    ),
                ),
                (
                    "npd_income_type",
                    models.CharField(
                        blank=True,
                        default="FROM_INDIVIDUAL",
                        help_text="Тип плательщика",
                        max_length=20,
                    ),
                ),
                (
                    "npd_income_inn",
                    models.PositiveIntegerField(
                        blank=True, help_text="ИНН плательщика", null=True
                    ),
                ),
                (
                    "npd_income_company",
                    models.CharField(
                        blank=True,
                        help_text="Название компании плательщика",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "link_expired",
                    models.DateTimeField(
                        blank=True, help_text="Срок действия ссылки", null=True
                    ),
                ),
                (
                    "paid_content",
                    models.TextField(
                        blank=True,
                        help_text="Текст для пользователя после оплаты",
                        null=True,
                    ),
                ),
                (
                    "ref",
                    models.CharField(
                        blank=True,
                        help_text="идентификатор партнера (ПРОМОКОД)",
                        max_length=40,
                        null=True,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        help_text="Если передано значение json, то ответ от Продамуса придет в формате json",
                        max_length=40,
                        null=True,
                    ),
                ),
                (
                    "callbackType",
                    models.CharField(
                        blank=True,
                        help_text="Если передано значение json, то веб-хуки от Продамуса будут приходить в формате json",
                        max_length=40,
                        null=True,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        blank=True,
                        help_text="Валюта платежа. Возможные значения: rub, usd, eur, kzt",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "payments_limit",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Лимит оплат по сформированной ссылке",
                        null=True,
                        verbose_name="Лимит оплат по сформированной ссылке",
                    ),
                ),
                (
                    "acquiring",
                    models.CharField(
                        blank=True,
                        help_text="Эквайринг.Возможные значения: sbrf, monet, qiwi, xpay, xpaykz",
                        max_length=40,
                        null=True,
                        verbose_name="Эквайринг",
                    ),
                ),
                (
                    "signature",
                    models.CharField(
                        blank=True,
                        help_text="Подпись, создаваемая на основе секретного ключа и данных для создания ссылки",
                        max_length=64,
                        null=True,
                        verbose_name="Подпись запроса",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ссылка на платеж Prodamus",
                "verbose_name_plural": "Ссылки на платежи Prodamus",
            },
        ),
    ]
