# Generated by Django 4.1.1 on 2024-04-27 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0023_rename_schoolpaymentlink_schoolexpresspaylink"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolStudentsTableSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_students_grouped",
                    models.BooleanField(
                        default=True,
                        help_text="Сгруппированы ли студенты в таблице",
                        verbose_name="Сгруппированы ли студенты в таблице",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="schools.school"
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройки группировки студентов",
                "verbose_name_plural": "Настройки группировки студентов",
            },
        ),
    ]
