# Generated by Django 4.1.1 on 2024-04-28 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0023_schoolpaymentmethod_payment_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="prodamuspaymentlink",
            name="school_payment_method",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="schools.schoolpaymentmethod",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="schoolpaymentmethod",
            name="payment_url",
            field=models.URLField(
                blank=True,
                default=None,
                help_text="Ссылка платежного кабинета Продамус",
                max_length=250,
                null=True,
                verbose_name="URL платежного кабинета",
            ),
        ),
    ]
