# Generated by Django 4.1.1 on 2024-04-30 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0024_schoolstudentstablesettings"),
        ("schools", "0026_prodamuspaymentlink_school_payment_method_and_more"),
    ]

    operations = []
