# Generated by Django 4.1.1 on 2024-05-07 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0037_merge_20240423_0604"),
        ("schools", "0027_merge_20240430_1714"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolMeetings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.URLField(verbose_name="Ссылка для перехода на митинг")),
                (
                    "created",
                    models.DateTimeField(
                        help_text="Дата и время начала ссылки",
                        verbose_name="Дата и время начала ссылки",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="schools.school"
                    ),
                ),
                ("students_groups", models.ManyToManyField(to="courses.studentsgroup")),
            ],
            options={
                "verbose_name": "Ссылка на митинг",
                "verbose_name_plural": "Ссылки на митинг",
            },
        ),
    ]
