# Generated by Django 4.1.1 on 2024-05-07 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0028_schoolmeetings"),
    ]

    operations = [
        migrations.RenameField(
            model_name="schoolmeetings",
            old_name="created",
            new_name="start_date",
        ),
    ]
