# Generated by Django 4.1.1 on 2024-05-13 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0029_rename_created_schoolmeetings_start_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schoolmeetings",
            name="school",
        ),
        migrations.AlterField(
            model_name="schoolmeetings",
            name="start_date",
            field=models.DateTimeField(
                help_text="Дата и время начала миттинга",
                verbose_name="Дата и время начала миттинга",
            ),
        ),
    ]
