# Generated by Django 4.1.1 on 2024-05-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0039_alter_groupcourseaccess_options_and_more"),
        ("schools", "0030_remove_schoolmeetings_school_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schoolmeetings",
            name="students_groups",
            field=models.ManyToManyField(
                related_name="school_meetings", to="courses.studentsgroup"
            ),
        ),
    ]
