# Generated by Django 4.1.1 on 2024-05-29 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0032_domain"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="domain",
            name="is_verified",
        ),
    ]
