# Generated by Django 4.1.1 on 2024-05-30 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0033_remove_domain_is_verified"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="domain",
            options={"verbose_name": "Домен", "verbose_name_plural": "Домены"},
        ),
        migrations.AlterField(
            model_name="domain",
            name="domain_name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="domain",
            name="school",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="domain",
                to="schools.school",
            ),
        ),
    ]
