# Generated by Django 4.1.1 on 2024-06-13 10:37

import django.db.models.deletion
from django.db import migrations, models


def add_tasks_to_existing_schools(apps, schema_editor):
    School = apps.get_model("schools", "School")
    SchoolTask = apps.get_model("schools", "SchoolTask")
    tasks = [
        ("create_course", "Создать свой курс"),
        ("create_first_lesson", "Создать свой первый урок"),
        ("upload_video", "Загрузить видео в урок"),
        ("publish_course", "Опубликовать курс в каталоге"),
        ("add_first_staff", "Добавить первого сотрудника"),
        ("create_first_group", "Создать первую группу"),
        ("add_first_student", "Добавить первого ученика"),
    ]

    for school in School.objects.all():
        for task_choice in tasks:
            SchoolTask.objects.get_or_create(school=school, task=task_choice[0])


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0034_alter_domain_options_alter_domain_domain_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task",
                    models.CharField(
                        choices=[
                            ("create_course", "Создать свой курс"),
                            ("create_first_lesson", "Создать свой первый урок"),
                            ("upload_video", "Загрузить видео в урок"),
                            ("publish_course", "Опубликовать курс в каталоге"),
                            ("add_first_staff", "Добавить первого сотрудника"),
                            ("create_first_group", "Создать первую группу"),
                            ("add_first_student", "Добавить первого ученика"),
                        ],
                        max_length=50,
                        verbose_name="Задача",
                    ),
                ),
                (
                    "completed",
                    models.BooleanField(default=False, verbose_name="Выполнено"),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="schools.school",
                        verbose_name="Школа",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задача для школы",
                "verbose_name_plural": "Задачи для школ",
                "unique_together": {("school", "task")},
            },
        ),
        migrations.RunPython(add_tasks_to_existing_schools),
    ]
