# Generated by Django 4.1.1 on 2024-06-10 19:36

import common_services.services.file_validation
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0034_alter_domain_options_alter_domain_domain_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bonus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Логотип акции",
                        null=True,
                        upload_to=common_services.services.file_validation.TruncateFileName(
                            300
                        ),
                        validators=[
                            common_services.services.file_validation.limit_image_size
                        ],
                        verbose_name="Логотип",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        blank=True,
                        help_text="Описание акции",
                        null=True,
                        verbose_name="Описание",
                    ),
                ),
                ("link", models.URLField(verbose_name="Ссылка на акцию")),
                (
                    "expire_date",
                    models.DateTimeField(
                        help_text="Дата и время окончания акции",
                        verbose_name="Дата и время окончания акции",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=False,
                        help_text="Определяет, активирован ли бонус",
                        verbose_name="Активный",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        help_text="ID школы",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bonuses",
                        to="schools.school",
                        verbose_name="ID школы",
                    ),
                ),
            ],
            options={
                "verbose_name": "Бонус",
                "verbose_name_plural": "Бонусы",
            },
        ),
    ]
