# Generated by Django 4.1.1 on 2024-06-10 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0042_studentshistory_finish_date"),
        ("schools", "0035_bonus"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupBonus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bonus",
                    models.ForeignKey(
                        help_text="Предоставленный группе бонус",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schools.bonus",
                        verbose_name="Бонус",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        help_text="Группа, которой предоставлен бонус",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_bonuses",
                        to="courses.studentsgroup",
                        verbose_name="Группа",
                    ),
                ),
            ],
            options={
                "verbose_name": "Бонус для группы",
                "verbose_name_plural": "Бонусы для групп",
            },
        ),
    ]