# Generated by Django 4.1.1 on 2024-06-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0042_studentshistory_finish_date"),
        ("schools", "0036_groupbonus"),
    ]

    operations = [
        migrations.AddField(
            model_name="bonus",
            name="student_groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="Группы, которым предоставлен бонус",
                related_name="group_bonuses",
                to="courses.studentsgroup",
                verbose_name="Группы",
            ),
        ),
        migrations.DeleteModel(
            name="GroupBonus",
        ),
    ]
