# Generated by Django 4.1.1 on 2024-06-14 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0035_schooltask"),
        ("schools", "0037_bonus_student_groups_delete_groupbonus"),
    ]

    operations = []
