# Generated by Django 4.1.1 on 2024-06-23 19:51

import common_services.services.file_validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0037_bonus_student_groups_delete_groupbonus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bonus",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Логотип акции",
                max_length=300,
                null=True,
                upload_to=common_services.services.file_validation.TruncateFileName(
                    300
                ),
                validators=[common_services.services.file_validation.limit_image_size],
                verbose_name="Логотип",
            ),
        ),
    ]
