# Generated by Django 4.1.1 on 2024-06-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0038_merge_20240614_0927"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsletterTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "template_name",
                    models.CharField(max_length=255, verbose_name="Имя шаблона"),
                ),
                ("text", models.TextField(verbose_name="Текст шаблона")),
                (
                    "delay_days",
                    models.PositiveIntegerField(
                        verbose_name="Количество дней после регистрации для рассылки"
                    ),
                ),
                (
                    "template_created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время создания шаблона"
                    ),
                ),
            ],
            options={
                "verbose_name": "Шаблон для рассылки",
                "verbose_name_plural": "Шаблоны для рассылки",
            },
        ),
    ]
