# Generated by Django 4.1.1 on 2024-06-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0039_newslettertemplate"),
    ]

    operations = [
        migrations.AddField(
            model_name="newslettertemplate",
            name="is_public",
            field=models.BooleanField(
                default=False, verbose_name="Рассылать ли шаблон"
            ),
        ),
    ]
