# Generated by Django 4.1.1 on 2024-06-19 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0040_newslettertemplate_is_public"),
    ]

    operations = [
        migrations.CreateModel(
            name="SentNewsletter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время отправки"
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_newsletters",
                        to="schools.school",
                        verbose_name="Школа",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_newsletters",
                        to="schools.newslettertemplate",
                        verbose_name="Шаблон рассылки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отправленный шаблон",
                "verbose_name_plural": "Отправленные шаблоны",
            },
        ),
    ]
