# Generated by Django 4.1.1 on 2024-07-01 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0038_alter_bonus_logo"),
        ("schools", "0041_sentnewsletter"),
    ]

    operations = []
