# Generated by Django 4.1.1 on 2024-07-01 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0042_merge_0038_alter_bonus_logo_0041_sentnewsletter"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReferralCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Уникальный реферальный код",
                        max_length=20,
                        unique=True,
                        verbose_name="Реферальный код",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Дата и время создания кода",
                        verbose_name="Дата и время создания кода",
                    ),
                ),
                (
                    "school",
                    models.OneToOneField(
                        help_text="Школа, которой принадлежит реферальный код",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referral_code",
                        to="schools.school",
                        verbose_name="Школа",
                    ),
                ),
            ],
            options={
                "verbose_name": "Реферальный код",
                "verbose_name_plural": "Реферальные коды",
            },
        ),
        migrations.CreateModel(
            name="ReferralClick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        help_text="IP-адрес, с которого был совершен переход",
                        verbose_name="IP-адрес",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Дата и время перехода",
                        verbose_name="Дата и время перехода",
                    ),
                ),
                (
                    "referral_code",
                    models.ForeignKey(
                        help_text="Реферальный код, по которому был совершен переход",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clicks",
                        to="schools.referralcode",
                        verbose_name="Реферальный код",
                    ),
                ),
            ],
            options={
                "verbose_name": "Переход по реферальной ссылке",
                "verbose_name_plural": "Переходы по реферальным ссылкам",
            },
        ),
        migrations.CreateModel(
            name="Referral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Дата и время создания реферала",
                        verbose_name="Дата и время создания реферала",
                    ),
                ),
                (
                    "referred_school",
                    models.OneToOneField(
                        help_text="Привлеченная школа",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referred_by",
                        to="schools.school",
                        verbose_name="Привлеченная школа",
                    ),
                ),
                (
                    "referrer_school",
                    models.ForeignKey(
                        help_text="Школа-реферер",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referrals",
                        to="schools.school",
                        verbose_name="Школа-реферер",
                    ),
                ),
            ],
            options={
                "verbose_name": "Реферал",
                "verbose_name_plural": "Рефералы",
            },
        ),
    ]
