# Generated by Django 4.1.1 on 2024-07-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0044_remove_referralclick_referral_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="test_course",
            field=models.BooleanField(
                default=False,
                help_text="Включен ли тестовый курс для админов",
                verbose_name="Включен ли тестовый курс для админов",
            ),
        ),
    ]
