# Generated by Django 4.1.1 on 2024-07-24 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0050_auto_20240625_0802"),
        ("schools", "0045_school_test_course"),
    ]

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Заголовок баннера",
                        max_length=255,
                        verbose_name="Заголовок",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Описание баннера", verbose_name="Описание"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Активный баннер",
                        verbose_name="Активный",
                    ),
                ),
                (
                    "link",
                    models.URLField(
                        help_text="Ссылка на баннер",
                        max_length=255,
                        verbose_name="Ссылка",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        related_name="banners",
                        to="courses.studentsgroup",
                        verbose_name="Группы",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        help_text="Баннер школы",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="banners",
                        to="schools.school",
                        verbose_name="Баннер школы",
                    ),
                ),
            ],
            options={
                "verbose_name": "Баннер",
                "verbose_name_plural": "Баннеры",
            },
        ),
        migrations.CreateModel(
            name="BannerClick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Дата и время перехода",
                        verbose_name="Дата и время перехода",
                    ),
                ),
                (
                    "banner",
                    models.ForeignKey(
                        help_text="Баннер",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clicks",
                        to="schools.banner",
                        verbose_name="Баннер",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Пользователь",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="banner_clicks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Переход по баннеру",
                "verbose_name_plural": "Переходы по баннерам",
            },
        ),
        migrations.CreateModel(
            name="BannerAccept",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_accepted",
                    models.BooleanField(
                        default=False,
                        help_text="Пользователь принял баннер",
                        verbose_name="Пользователь принял баннер",
                    ),
                ),
                (
                    "banner",
                    models.ForeignKey(
                        help_text="Баннер",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accepts",
                        to="schools.banner",
                        verbose_name="Баннер",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Пользователь",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="banner_accepts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Принятый баннер",
                "verbose_name_plural": "Принятыe баннеры",
            },
        ),
    ]
