# Generated by Django 4.1.1 on 2024-09-05 08:21

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0046_banner_bannerclick_banneraccept"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="rebranding_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Активировать ребрендинг школы",
                verbose_name="Ребрендинг активирован",
            ),
        ),
        migrations.CreateModel(
            name="SchoolBranding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform_logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="branding/logos/",
                        verbose_name="Логотип платформы",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        help_text="Номер телефона",
                        max_length=128,
                        null=True,
                        region=None,
                        verbose_name="Номер телефона",
                    ),
                ),
                (
                    "unp",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="УНП"
                    ),
                ),
                (
                    "full_organization_name",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Полное название организации",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="Адрес"
                    ),
                ),
                (
                    "school",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branding",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ребрендинг школы",
                "verbose_name_plural": "Ребрендинги школ",
            },
        ),
    ]
