# Generated by Django 4.1.1 on 2024-10-14 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0048_schoolnewrole"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="banner",
            index=models.Index(
                fields=["is_active"], name="schools_ban_is_acti_94a53d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="banner",
            index=models.Index(
                fields=["school"], name="schools_ban_school__f43c6a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="banneraccept",
            index=models.Index(
                fields=["banner", "user"], name="schools_ban_banner__88cb0d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bannerclick",
            index=models.Index(
                fields=["timestamp"], name="schools_ban_timesta_b1109d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bonus",
            index=models.Index(
                fields=["school"], name="schools_bon_school__1c56c0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bonus",
            index=models.Index(
                fields=["expire_date"], name="schools_bon_expire__0e14c0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bonus",
            index=models.Index(fields=["active"], name="schools_bon_active_99ac64_idx"),
        ),
        migrations.AddIndex(
            model_name="domain",
            index=models.Index(
                fields=["domain_name"], name="schools_dom_domain__f61059_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="domain",
            index=models.Index(
                fields=["nginx_configured"], name="schools_dom_nginx_c_3f065b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="domain",
            index=models.Index(
                fields=["school"], name="schools_dom_school__396036_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="newslettertemplate",
            index=models.Index(
                fields=["template_name"], name="schools_new_templat_8b17b7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="promocode",
            index=models.Index(fields=["name"], name="schools_pro_name_f137e6_idx"),
        ),
        migrations.AddIndex(
            model_name="referral",
            index=models.Index(
                fields=["referrer_school"], name="schools_ref_referre_2fca4e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="referral",
            index=models.Index(
                fields=["referred_school"], name="schools_ref_referre_bbcbd9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="referral",
            index=models.Index(
                fields=["created_at"], name="schools_ref_created_bea952_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="referralclick",
            index=models.Index(
                fields=["school"], name="schools_ref_school__834705_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="referralclick",
            index=models.Index(
                fields=["timestamp"], name="schools_ref_timesta_097f3d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="school",
            index=models.Index(fields=["name"], name="schools_sch_name_5d0cfd_idx"),
        ),
        migrations.AddIndex(
            model_name="school",
            index=models.Index(
                fields=["tariff"], name="schools_sch_tariff__069195_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="school",
            index=models.Index(fields=["owner"], name="schools_sch_owner_i_bd0dc7_idx"),
        ),
        migrations.AddIndex(
            model_name="schoolbranding",
            index=models.Index(
                fields=["school"], name="schools_sch_school__e16933_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="schoolbranding",
            index=models.Index(fields=["email"], name="schools_sch_email_90eafe_idx"),
        ),
        migrations.AddIndex(
            model_name="schoolbranding",
            index=models.Index(fields=["phone"], name="schools_sch_phone_a4da2f_idx"),
        ),
        migrations.AddIndex(
            model_name="schooldocuments",
            index=models.Index(fields=["user"], name="schools_sch_user_id_f8c55b_idx"),
        ),
        migrations.AddIndex(
            model_name="schooldocuments",
            index=models.Index(
                fields=["school"], name="schools_sch_school__05dc0b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="schoolheader",
            index=models.Index(fields=["name"], name="schools_sch_name_4a363f_idx"),
        ),
        migrations.AddIndex(
            model_name="schoolheader",
            index=models.Index(
                fields=["school"], name="schools_sch_school__6db61a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="schoolmeetings",
            index=models.Index(
                fields=["start_date"], name="schools_sch_start_d_09df30_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="schoolnewrole",
            index=models.Index(
                fields=["school"], name="schools_sch_school__910b5b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="schoolnewrole",
            index=models.Index(fields=["user"], name="schools_sch_user_id_961be3_idx"),
        ),
        migrations.AddIndex(
            model_name="schoolnewrole",
            index=models.Index(
                fields=["role_name"], name="schools_sch_role_na_9f57a7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="schoolstatistics",
            index=models.Index(
                fields=["school"], name="schools_sch_school__90c6ee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sentnewsletter",
            index=models.Index(
                fields=["school"], name="schools_sen_school__7080af_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sentnewsletter",
            index=models.Index(
                fields=["template"], name="schools_sen_templat_bf75fd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tariff",
            index=models.Index(fields=["name"], name="schools_tar_name_8e5059_idx"),
        ),
        migrations.AddConstraint(
            model_name="school",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("tariff__isnull", False),
                    models.Q(
                        ("purchased_tariff_end_date__isnull", True),
                        ("trial_end_date__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="check_tariff_not_null_if_period_active",
            ),
        ),
    ]
