# Generated by Django 4.1.1 on 2024-12-02 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0049_banner_schools_ban_is_acti_94a53d_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="extra_link",
            field=models.URLField(
                blank=True,
                help_text="Дополнительная ссылка на ресурс",
                null=True,
                verbose_name="Дополнительная ссылка",
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="instagram_link",
            field=models.URLField(
                blank=True,
                help_text="Ссылка на Instagram",
                null=True,
                verbose_name="Ссылка на Instagram",
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="telegram_link",
            field=models.URLField(
                blank=True,
                help_text="Ссылка на Telegram",
                null=True,
                verbose_name="Ссылка на Telegram",
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="twitter_link",
            field=models.URLField(
                blank=True,
                help_text="Ссылка на Twitter",
                null=True,
                verbose_name="Ссылка на Twitter",
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="vk_link",
            field=models.URLField(
                blank=True,
                help_text="Ссылка на ВКонтакте",
                null=True,
                verbose_name="Ссылка на ВКонтакте",
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="youtube_link",
            field=models.URLField(
                blank=True,
                help_text="Ссылка на YouTube",
                null=True,
                verbose_name="Ссылка на YouTube",
            ),
        ),
    ]
