# Generated by Django 4.1.1 on 2024-11-15 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0049_banner_schools_ban_is_acti_94a53d_idx_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="school",
            name="check_tariff_not_null_if_period_active",
        ),
    ]
