# Generated by Django 4.1.1 on 2024-12-13 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0051_box_prize_userprize_payment_boxprize"),
    ]

    operations = [
        migrations.AlterField(
            model_name="box",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Цена коробки",
                max_digits=10,
                verbose_name="Цена",
            ),
        ),
    ]
