# Generated by Django 4.1.1 on 2024-12-13 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0052_alter_box_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="boxprize",
            name="count_in_box",
        ),
    ]
