# Generated by Django 4.1.1 on 2024-12-17 19:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0053_remove_boxprize_count_in_box"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="invoice_no",
            field=models.IntegerField(
                default=0,
                help_text="Номер счета",
                null=True,
                verbose_name="Номер счета",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="school",
            field=models.ForeignKey(
                default=1,
                help_text="ID школы",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="schools.school",
                verbose_name="ID школы",
            ),
            preserve_default=False,
        ),
    ]
