# Generated by Django 4.1.1 on 2024-12-19 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0055_userbox"),
    ]

    operations = [
        migrations.AddField(
            model_name="userbox",
            name="opened_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Открытые коробки"
            ),
        ),
    ]
