# Generated by Django 4.1.1 on 2024-12-19 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0056_userbox_opened_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprize",
            name="is_used",
            field=models.BooleanField(
                default=False, help_text="Приз использован", verbose_name="Использован"
            ),
        ),
    ]
