# Generated by Django 4.1.1 on 2024-12-23 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0050_remove_school_check_tariff_not_null_if_period_active"),
        ("schools", "0057_userprize_is_used"),
    ]

    operations = []
