# Generated by Django 4.1.1 on 2025-01-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0058_merge_20241223_1013"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolmeetings",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Описание миттинга"
            ),
        ),
        migrations.AddField(
            model_name="schoolmeetings",
            name="title",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Название миттинга"
            ),
        ),
    ]
