# Generated by Django 4.1.1 on 2025-02-20 10:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0059_schoolmeetings_description_schoolmeetings_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="bonus",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Дата и время, когда запись была создана",
                verbose_name="Создано",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bonus",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Дата, когда запись была последний раз обновлена",
                verbose_name="Обновлено",
            ),
        ),
    ]
