# Generated by Django 4.1.1 on 2025-02-20 13:19

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0060_bonus_created_at_bonus_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="bonus",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(
                blank=True, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="bonus",
            index=models.Index(
                fields=["search_vector"], name="schools_bon_search__44474f_idx"
            ),
        ),
    ]
