# Generated by Django 4.1.1 on 2025-04-02 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0067_comment_parent_comment"),
        ("schools", "0061_bonus_search_vector_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InviteProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Активация программы",
                        verbose_name="Активный",
                    ),
                ),
                (
                    "link",
                    models.URLField(
                        help_text="Реферальная ссылка",
                        max_length=255,
                        verbose_name="Ссылка",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        related_name="invite_program",
                        to="courses.studentsgroup",
                        verbose_name="Группы",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        help_text="инвайт-программa",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invite_program",
                        to="schools.school",
                        verbose_name="инвайт-программa",
                    ),
                ),
            ],
            options={
                "verbose_name": "инвайт-программа",
                "verbose_name_plural": "инвайт-программы",
            },
        ),
        migrations.AddIndex(
            model_name="inviteprogram",
            index=models.Index(
                fields=["is_active"], name="schools_inv_is_acti_047583_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inviteprogram",
            index=models.Index(
                fields=["school"], name="schools_inv_school__934935_idx"
            ),
        ),
    ]
