# Generated by Django 4.1.1 on 2025-04-03 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0062_inviteprogram_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inviteprogram",
            name="link",
            field=models.URLField(
                blank=True,
                help_text="Реферальная ссылка",
                max_length=255,
                null=True,
                verbose_name="Ссылка",
            ),
        ),
    ]
