# Generated by Django 5.2.5 on 2025-08-11 18:18

import common_services.services.file_validation
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('GROUP', 'Group'), ('PERSONAL', 'Personal'), ('COURSE', 'Course'), ('ADMIN', 'Admin')], default=None, max_length=10)),
            ],
            options={
                'verbose_name': 'Чат',
                'verbose_name_plural': 'Чаты',
            },
        ),
        migrations.CreateModel(
            name='UserChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role', models.CharField(max_length=50, verbose_name='Роль пользователя')),
                ('unread_messages_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Пользователь чата',
                'verbose_name_plural': 'Пользователи чата',
            },
        ),
        migrations.CreateModel(
            name='ChatLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_from', to='chats.chat')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_to', to='chats.chat')),
            ],
        ),
        migrations.AddField(
            model_name='chat',
            name='personal_chats',
            field=models.ManyToManyField(blank=True, related_name='group_chats', through='chats.ChatLink', to='chats.chat'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('file', models.FileField(blank=True, help_text='Прикрепленный файл', max_length=300, null=True, upload_to=common_services.services.file_validation.TruncateFileName(300), validators=[common_services.services.file_validation.limit_size], verbose_name='Прикрепленный файл')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.chat')),
            ],
            options={
                'verbose_name': 'Сообщение чата',
                'verbose_name_plural': 'Сообщения чата',
            },
        ),
    ]
