# Generated by Django 5.2.5 on 2025-08-11 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userchat',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.chat'),
        ),
        migrations.AddField(
            model_name='userchat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['name'], name='chats_chat_name_462ed6_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['type'], name='chats_chat_type_53bf85_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat'], name='chats_messa_chat_id_0c8f01_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender'], name='chats_messa_sender__411bbf_idx'),
        ),
        migrations.AddIndex(
            model_name='userchat',
            index=models.Index(fields=['chat'], name='chats_userc_chat_id_cf4425_idx'),
        ),
        migrations.AddIndex(
            model_name='userchat',
            index=models.Index(fields=['user'], name='chats_userc_user_id_c7f52e_idx'),
        ),
        migrations.AddIndex(
            model_name='userchat',
            index=models.Index(fields=['user_role'], name='chats_userc_user_ro_213b92_idx'),
        ),
    ]
