# Generated by Django 4.1.1 on 2023-10-07 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links_from",
                        to="chats.chat",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links_to",
                        to="chats.chat",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="chat",
            name="personal_chats",
            field=models.ManyToManyField(
                blank=True,
                related_name="group_chats",
                through="chats.ChatLink",
                to="chats.chat",
            ),
        ),
    ]
