# Generated by Django 4.2.6 on 2023-10-14 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0003_chatlink_chat_personal_chats"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="type",
            field=models.CharField(
                choices=[
                    ("GROUP", "Group"),
                    ("PERSONAL", "Personal"),
                    ("COURSE", "Course"),
                ],
                default=None,
                max_length=10,
            ),
        ),
    ]
