# Generated by Django 4.1.1 on 2023-12-23 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0004_alter_chat_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="read_by",
        ),
    ]
