# Generated by Django 4.1.1 on 2023-12-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0005_remove_message_read_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="userchat",
            name="unread_messages_count",
            field=models.IntegerField(default=0),
        ),
    ]
