# Generated by Django 4.1.1 on 2023-12-25 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0006_remove_message_read_by"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UnreadMessage",
        ),
    ]
