# Generated by Django 4.1.1 on 2024-01-25 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0006_userchat_unread_messages_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="type",
            field=models.CharField(
                choices=[
                    ("GROUP", "Group"),
                    ("PERSONAL", "Personal"),
                    ("COURSE", "Course"),
                    ("ADMIN", "Admin"),
                ],
                default=None,
                max_length=10,
            ),
        ),
    ]
