# Generated by Django 4.1.1 on 2024-01-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0007_alter_chat_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="userchat",
            name="user_role",
            field=models.CharField(
                default=1, max_length=50, verbose_name="Роль пользователя"
            ),
            preserve_default=False,
        ),
    ]
