# Generated by Django 4.1.1 on 2024-10-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0008_userchat_user_role"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chat",
            options={"verbose_name": "Чат", "verbose_name_plural": "Чаты"},
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "verbose_name": "Сообщение чата",
                "verbose_name_plural": "Сообщения чата",
            },
        ),
        migrations.AlterModelOptions(
            name="userchat",
            options={
                "verbose_name": "Пользователь чата",
                "verbose_name_plural": "Пользователи чата",
            },
        ),
        migrations.AddIndex(
            model_name="chat",
            index=models.Index(fields=["name"], name="chats_chat_name_462ed6_idx"),
        ),
        migrations.AddIndex(
            model_name="chat",
            index=models.Index(fields=["type"], name="chats_chat_type_53bf85_idx"),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["chat"], name="chats_messa_chat_id_0c8f01_idx"),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["sender"], name="chats_messa_sender__411bbf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userchat",
            index=models.Index(fields=["chat"], name="chats_userc_chat_id_cf4425_idx"),
        ),
        migrations.AddIndex(
            model_name="userchat",
            index=models.Index(fields=["user"], name="chats_userc_user_id_c7f52e_idx"),
        ),
        migrations.AddIndex(
            model_name="userchat",
            index=models.Index(
                fields=["user_role"], name="chats_userc_user_ro_213b92_idx"
            ),
        ),
    ]
