# Generated by Django 4.1.1 on 2025-01-13 08:47

import common_services.services.file_validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0009_alter_chat_options_alter_message_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="Прикрепленный файл",
                max_length=300,
                null=True,
                upload_to=common_services.services.file_validation.TruncateFileName(
                    300
                ),
                validators=[common_services.services.file_validation.limit_size],
                verbose_name="Прикрепленный файл",
            ),
        ),
    ]
