# Generated by Django 4.1.1 on 2024-04-23 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TgUsers",
            fields=[
                (
                    "id",
                    models.AutoField(
                        editable=False,
                        help_text="Уникальный идентификатор пользователя",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID пользователя",
                    ),
                ),
                (
                    "tg_user_id",
                    models.CharField(
                        editable=False,
                        max_length=10,
                        verbose_name="Телеграм ID пользователя",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="Имя"
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь плтаформы",
                    ),
                ),
            ],
            options={
                "verbose_name": "Телеграм пользователь",
                "verbose_name_plural": "Телеграм пользователи",
            },
        ),
        migrations.CreateModel(
            name="Notifications",
            fields=[
                (
                    "id",
                    models.AutoField(
                        editable=False,
                        help_text="Уникальный идентификатор пользователя",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID уведомлений для телеграм пользователя",
                    ),
                ),
                (
                    "homework_notifications",
                    models.CharField(
                        editable=False,
                        max_length=10,
                        verbose_name="Телеграм ID пользователя",
                    ),
                ),
                (
                    "messages_notifications",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="Имя"
                    ),
                ),
                (
                    "tg_user_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tg_notifications.tgusers",
                        verbose_name="Телеграм пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Телеграм пользователь",
                "verbose_name_plural": "Телеграм пользователи",
            },
        ),
    ]
