# Generated by Django 5.2.5 on 2025-08-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedCoursesNotificationsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MeetingsRemindersTG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily', models.BooleanField(default=False)),
                ('in_three_hours', models.BooleanField(default=False)),
                ('ten_minute', models.BooleanField(default=False)),
                ('sent', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(editable=False, help_text='Уникальный идентификатор пользователя', primary_key=True, serialize=False, verbose_name='ID уведомлений для телеграм пользователя')),
                ('homework_notifications', models.BooleanField(default=True, verbose_name='Уведомления о проверке домашних заданий')),
                ('messages_notifications', models.BooleanField(default=True, verbose_name='Уведомления о поступлении сообщений с платформы')),
                ('completed_courses_notifications', models.BooleanField(default=True, verbose_name='Уведомления о прохождении курса учеником')),
            ],
            options={
                'verbose_name': 'Телеграм уведомление',
                'verbose_name_plural': 'Телеграм уведомления',
            },
        ),
        migrations.CreateModel(
            name='TgUsers',
            fields=[
                ('id', models.AutoField(editable=False, help_text='Уникальный идентификатор пользователя', primary_key=True, serialize=False, verbose_name='ID пользователя')),
                ('tg_user_id', models.CharField(editable=False, max_length=10, verbose_name='Телеграм ID пользователя')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Телеграм пользователь',
                'verbose_name_plural': 'Телеграм пользователи',
            },
        ),
    ]
