# Generated by Django 4.1.1 on 2024-04-23 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tg_notifications", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notifications",
            old_name="tg_user_id",
            new_name="tg_user",
        ),
        migrations.RenameField(
            model_name="tgusers",
            old_name="user_id",
            new_name="user",
        ),
    ]
