# Generated by Django 5.2.5 on 2025-08-11 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0002_initial'),
        ('tg_notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='completedcoursesnotificationslog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meetingsreminderstg',
            name='meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.schoolmeetings'),
        ),
        migrations.AddField(
            model_name='tgusers',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь плтаформы'),
        ),
        migrations.AddField(
            model_name='notifications',
            name='tg_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tg_notifications.tgusers', verbose_name='Телеграм пользователь'),
        ),
        migrations.AlterUniqueTogether(
            name='completedcoursesnotificationslog',
            unique_together={('user', 'course_id')},
        ),
    ]
