# Generated by Django 4.1.1 on 2024-04-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tg_notifications", "0002_rename_tg_user_id_notifications_tg_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notifications",
            name="homework_notifications",
            field=models.BooleanField(
                default=False, verbose_name="Уведомления о проверке домашних заданий"
            ),
        ),
        migrations.AlterField(
            model_name="notifications",
            name="messages_notifications",
            field=models.BooleanField(
                default=False,
                verbose_name="Уведомления о поступлении сообщений с платформы",
            ),
        ),
    ]
