# Generated by Django 4.1.1 on 2024-05-02 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "tg_notifications",
            "0003_alter_notifications_homework_notifications_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notifications",
            options={
                "verbose_name": "Телеграм уведомление",
                "verbose_name_plural": "Телеграм уведомления",
            },
        ),
        migrations.AlterField(
            model_name="notifications",
            name="homework_notifications",
            field=models.BooleanField(
                default=True, verbose_name="Уведомления о проверке домашних заданий"
            ),
        ),
        migrations.AlterField(
            model_name="notifications",
            name="messages_notifications",
            field=models.BooleanField(
                default=True,
                verbose_name="Уведомления о поступлении сообщений с платформы",
            ),
        ),
    ]
