# Generated by Django 4.1.1 on 2024-05-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tg_notifications", "0004_alter_notifications_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notifications",
            name="copleted_courcses_notifications",
            field=models.BooleanField(
                default=True, verbose_name="Уведомления о прохождении курса учеником"
            ),
        ),
    ]
