# Generated by Django 4.1.1 on 2024-05-09 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tg_notifications", "0005_notifications_copleted_courcses_notifications"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notifications",
            old_name="copleted_courcses_notifications",
            new_name="completed_courses_notifications",
        ),
    ]
