# Generated by Django 4.1.1 on 2024-06-04 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0039_alter_groupcourseaccess_options_and_more"),
        ("tg_notifications", "0007_completedcoursesnotificationslog"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeetingsReminders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_time", models.DateTimeField()),
                ("daily", models.BooleanField(default=False)),
                ("hourly", models.BooleanField(default=False)),
                ("half_hourly", models.BooleanField(default=False)),
                ("ten_minute", models.BooleanField(default=False)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.studentsgroup",
                    ),
                ),
            ],
        ),
    ]
