# Generated by Django 4.2.16 on 2025-07-06 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0063_alter_inviteprogram_link"),
        ("tg_notifications", "0007_completedcoursesnotificationslog"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeetingsRemindersTG",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("daily", models.BooleanField(default=False)),
                ("in_three_hours", models.BooleanField(default=False)),
                ("ten_minute", models.BooleanField(default=False)),
                ("sent", models.BooleanField(default=False)),
                (
                    "meeting",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schools.schoolmeetings",
                    ),
                ),
            ],
        ),
    ]
