# Generated by Django 4.1.1 on 2024-06-13 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tg_notifications", "0008_meetingsreminderstg"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MeetingsRemindersTG",
        ),
    ]
