# Generated by Django 4.1.1 on 2024-06-13 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tg_notifications", "0008_meetingsreminders"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MeetingsReminders",
        ),
    ]
