# Generated by Django 4.1.1 on 2024-06-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0050_auto_20240625_0802"),
        ("tg_notifications", "0009_delete_meetingsreminders"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeetingsRemindersTG",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_time", models.DateTimeField()),
                ("daily", models.BooleanField(default=False)),
                ("in_three_hours", models.BooleanField(default=False)),
                ("ten_minute", models.BooleanField(default=True)),
                ("sent", models.BooleanField(default=False)),
                (
                    "students_groups",
                    models.ManyToManyField(
                        related_name="meetings_reminders", to="courses.studentsgroup"
                    ),
                ),
            ],
        ),
    ]
