# Generated by Django 4.1.1 on 2024-07-02 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0042_merge_0038_alter_bonus_logo_0041_sentnewsletter"),
        ("tg_notifications", "0010_meetingsreminderstg"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meetingsreminderstg",
            name="event_time",
        ),
        migrations.RemoveField(
            model_name="meetingsreminderstg",
            name="students_groups",
        ),
        migrations.AddField(
            model_name="meetingsreminderstg",
            name="meeting",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="schools.schoolmeetings",
            ),
        ),
        migrations.AlterField(
            model_name="meetingsreminderstg",
            name="ten_minute",
            field=models.BooleanField(default=False),
        ),
    ]
